package InterfazJavaEat;


//IMPORTES
import ClasesJavaEat.Comida;
import ClasesJavaEat.Direccion;
import ClasesJavaEat.Restaurante;
import ClasesJavaEat.Sistema;
import java.awt.Color;
import java.io.Serializable;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;




/**
 * -Interfaz en la que el usuario puede crear un restaurante
 * @author David Sanchez
 * @version 1.0
 * @since 23/05/2023
 * @see Comida
 * @see Direccion
 * @see Restaurante
 * @see Sistema
 * @see Color
 * @see Serializable
 * @see ArrayList
 * @see DefaultListModel
 * @see ImageIcon
 * @see JOptionPane
 */
public class CrearRestaurante extends javax.swing.JFrame implements Serializable{

    
    int xMouse,yMouse;
    private boolean servicioCatering;
    private static ArrayList<Comida> listaMenu = new ArrayList<>();
    DefaultListModel modeloComidas = new DefaultListModel();           //Creamos un modelo para comidasLista(JList)
    
    
    
    //SETTERS
    public static void setListaMenu(ArrayList<Comida> listaMenu){CrearRestaurante.listaMenu = listaMenu;}

    //GETTERS
    public static ArrayList<Comida> getListaMenu(){return listaMenu;}
    
    
    /**
     * Inicia la interfaz CrearRestaurante
     */
    public CrearRestaurante() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //Actualizamos los datos como siempre
        Sistema.cargarDatosClientes();
        Sistema.cargarDatosEmpresas();
        Sistema.cargarDatosRestaurantes();
        Sistema.cargarDatosComidas();
        Sistema.cargarDatosVentasClientes();
        Sistema.cargarDatosVentasEmpresas();
        Sistema.cargarDatosVentasCatering();
        
        //Como el servicio de catering aparece marcado
        servicioCatering = true;
        
        //Le damos un modelo a usuariosLista(JList)
        comidasLista.setModel(modeloComidas);
        
        //Quitamos todos los datos que haya en las dos listas (Para poner los actalizados)
        modeloComidas.removeAllElements();
        
        /*
        Añadimos todos las comidas (Se puede hacer todo en una sola linea de codigo para ahorrar espacio 
        en memoria pero se a optado por obtener mejor claridad).
        */
        for(Comida comida : Sistema.getListaComidas())
        
        {
            String nombre = comida.getNombreComida();
            String ingredientes = comida.getIngredientes().toString();
            String precio = comida.getPrecio();

            String txt = nombre+", ("+precio+"€)"+"    Contiene los ingredientes"+ingredientes+".";
            modeloComidas.addElement(txt);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        FondoVerdeDerecha = new javax.swing.JPanel();
        javaTexto = new javax.swing.JLabel();
        eatsTexto = new javax.swing.JLabel();
        cerrarSesionTexto = new javax.swing.JLabel();
        atrasBoton = new javax.swing.JButton();
        hechoBoton = new javax.swing.JButton();
        BarraFunciones = new javax.swing.JPanel();
        botonExit = new javax.swing.JPanel();
        exitTexto = new javax.swing.JLabel();
        nombreInfo = new javax.swing.JTextField();
        gastosEnvioInfo = new javax.swing.JFormattedTextField();
        nombreTexto = new javax.swing.JLabel();
        crearRestauranteTexto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cifTexto = new javax.swing.JLabel();
        especialidadTexto = new javax.swing.JLabel();
        direccionTexto = new javax.swing.JLabel();
        gastosEnvioTexto = new javax.swing.JLabel();
        especialidadInfo = new javax.swing.JTextField();
        tiempoEnvioInfo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        cifInfo = new javax.swing.JFormattedTextField();
        calleTexto = new javax.swing.JLabel();
        numeroTexto = new javax.swing.JLabel();
        calleInfo = new javax.swing.JTextField();
        numeroInfo = new javax.swing.JTextField();
        codigoPostaltexto = new javax.swing.JLabel();
        codigoPostalInfo = new javax.swing.JFormattedTextField();
        ciudadTexto = new javax.swing.JLabel();
        ciudadInfo = new javax.swing.JTextField();
        tiempoEnvioTexto = new javax.swing.JLabel();
        textoExtra = new javax.swing.JLabel();
        servicioCateringBox = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        comidasLista = new javax.swing.JList<>();
        annadirBoton = new javax.swing.JButton();
        extraTiempoEnvioTexto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoVerdeDerecha.setBackground(new java.awt.Color(6, 193, 103));

        javaTexto.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        javaTexto.setForeground(new java.awt.Color(0, 0, 0));
        javaTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        javaTexto.setText("JAVA");

        eatsTexto.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        eatsTexto.setForeground(new java.awt.Color(0, 0, 0));
        eatsTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eatsTexto.setText("EATS");

        cerrarSesionTexto.setBackground(new java.awt.Color(255, 255, 255));
        cerrarSesionTexto.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        cerrarSesionTexto.setForeground(new java.awt.Color(0, 0, 0));
        cerrarSesionTexto.setText("Cerrar Sesión");
        cerrarSesionTexto.setBorder(null);
        cerrarSesionTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrarSesionTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarSesionTextoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarSesionTextoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarSesionTextoMouseExited(evt);
            }
        });

        atrasBoton.setBackground(new java.awt.Color(6, 193, 103));
        atrasBoton.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        atrasBoton.setForeground(new java.awt.Color(0, 0, 0));
        atrasBoton.setBorder(null);
        atrasBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atrasBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atrasBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atrasBotonMouseExited(evt);
            }
        });
        atrasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBotonActionPerformed(evt);
            }
        });

        hechoBoton.setBackground(new java.awt.Color(6, 193, 103));
        hechoBoton.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        hechoBoton.setForeground(new java.awt.Color(0, 0, 0));
        hechoBoton.setText("¡HECHO!");
        hechoBoton.setBorder(null);
        hechoBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hechoBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hechoBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hechoBotonMouseExited(evt);
            }
        });
        hechoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hechoBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoVerdeDerechaLayout = new javax.swing.GroupLayout(FondoVerdeDerecha);
        FondoVerdeDerecha.setLayout(FondoVerdeDerechaLayout);
        FondoVerdeDerechaLayout.setHorizontalGroup(
            FondoVerdeDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eatsTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addComponent(javaTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoVerdeDerechaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FondoVerdeDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoVerdeDerechaLayout.createSequentialGroup()
                        .addComponent(cerrarSesionTexto)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoVerdeDerechaLayout.createSequentialGroup()
                        .addComponent(hechoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoVerdeDerechaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(atrasBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        FondoVerdeDerechaLayout.setVerticalGroup(
            FondoVerdeDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoVerdeDerechaLayout.createSequentialGroup()
                .addComponent(cerrarSesionTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(javaTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eatsTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(hechoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addComponent(atrasBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        atrasBoton.setIcon(new ImageIcon("Imagenes/logoAtras.png"));

        background.add(FondoVerdeDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 250, 610));

        BarraFunciones.setBackground(new java.awt.Color(255, 255, 255));
        BarraFunciones.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraFuncionesMouseDragged(evt);
            }
        });
        BarraFunciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraFuncionesMousePressed(evt);
            }
        });

        botonExit.setBackground(new java.awt.Color(255, 255, 255));

        exitTexto.setBackground(new java.awt.Color(255, 255, 255));
        exitTexto.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        exitTexto.setForeground(new java.awt.Color(0, 0, 0));
        exitTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTexto.setText("X");
        exitTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTextoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTextoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTextoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botonExitLayout = new javax.swing.GroupLayout(botonExit);
        botonExit.setLayout(botonExitLayout);
        botonExitLayout.setHorizontalGroup(
            botonExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        botonExitLayout.setVerticalGroup(
            botonExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BarraFuncionesLayout = new javax.swing.GroupLayout(BarraFunciones);
        BarraFunciones.setLayout(BarraFuncionesLayout);
        BarraFuncionesLayout.setHorizontalGroup(
            BarraFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraFuncionesLayout.createSequentialGroup()
                .addComponent(botonExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        BarraFuncionesLayout.setVerticalGroup(
            BarraFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraFuncionesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(BarraFunciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 40));

        nombreInfo.setBackground(new java.awt.Color(255, 255, 255));
        nombreInfo.setForeground(new java.awt.Color(0, 0, 0));
        nombreInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        nombreInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreInfoActionPerformed(evt);
            }
        });
        background.add(nombreInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 260, 40));

        gastosEnvioInfo.setBackground(new java.awt.Color(255, 255, 255));
        gastosEnvioInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        gastosEnvioInfo.setForeground(new java.awt.Color(0, 0, 0));
        try {
            gastosEnvioInfo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        gastosEnvioInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gastosEnvioInfoActionPerformed(evt);
            }
        });
        background.add(gastosEnvioInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 260, 40));

        nombreTexto.setBackground(new java.awt.Color(6, 193, 103));
        nombreTexto.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        nombreTexto.setForeground(new java.awt.Color(0, 0, 0));
        nombreTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nombreTexto.setText("Nombre ");
        background.add(nombreTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 60, 20));

        crearRestauranteTexto.setBackground(new java.awt.Color(6, 193, 103));
        crearRestauranteTexto.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        crearRestauranteTexto.setForeground(new java.awt.Color(0, 0, 0));
        crearRestauranteTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        crearRestauranteTexto.setText("Crear restaurante");
        background.add(crearRestauranteTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 440, 60));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 680, 10));

        cifTexto.setBackground(new java.awt.Color(6, 193, 103));
        cifTexto.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        cifTexto.setForeground(new java.awt.Color(0, 0, 0));
        cifTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cifTexto.setText("CIF");
        background.add(cifTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 60, 20));

        especialidadTexto.setBackground(new java.awt.Color(6, 193, 103));
        especialidadTexto.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        especialidadTexto.setForeground(new java.awt.Color(0, 0, 0));
        especialidadTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        especialidadTexto.setText("Especialidad");
        background.add(especialidadTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 90, 20));

        direccionTexto.setBackground(new java.awt.Color(6, 193, 103));
        direccionTexto.setFont(new java.awt.Font("Roboto Medium", 2, 18)); // NOI18N
        direccionTexto.setForeground(new java.awt.Color(0, 0, 0));
        direccionTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        direccionTexto.setText("DIRECCIÓN");
        background.add(direccionTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 100, 20));

        gastosEnvioTexto.setBackground(new java.awt.Color(6, 193, 103));
        gastosEnvioTexto.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        gastosEnvioTexto.setForeground(new java.awt.Color(0, 0, 0));
        gastosEnvioTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gastosEnvioTexto.setText("Gastos Envio");
        background.add(gastosEnvioTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 90, 20));

        especialidadInfo.setBackground(new java.awt.Color(255, 255, 255));
        especialidadInfo.setForeground(new java.awt.Color(0, 0, 0));
        especialidadInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        especialidadInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialidadInfoActionPerformed(evt);
            }
        });
        background.add(especialidadInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 260, 40));

        tiempoEnvioInfo.setBackground(new java.awt.Color(255, 255, 255));
        tiempoEnvioInfo.setForeground(new java.awt.Color(0, 0, 0));
        tiempoEnvioInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tiempoEnvioInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoEnvioInfoActionPerformed(evt);
            }
        });
        background.add(tiempoEnvioInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 100, 40));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 970, 20));

        cifInfo.setBackground(new java.awt.Color(255, 255, 255));
        cifInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cifInfo.setForeground(new java.awt.Color(0, 0, 0));
        try {
            cifInfo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U-########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cifInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cifInfoActionPerformed(evt);
            }
        });
        background.add(cifInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 260, 40));

        calleTexto.setBackground(new java.awt.Color(6, 193, 103));
        calleTexto.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        calleTexto.setForeground(new java.awt.Color(0, 0, 0));
        calleTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        calleTexto.setText("Calle");
        background.add(calleTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 40, 20));

        numeroTexto.setBackground(new java.awt.Color(6, 193, 103));
        numeroTexto.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        numeroTexto.setForeground(new java.awt.Color(0, 0, 0));
        numeroTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        numeroTexto.setText("Numero");
        background.add(numeroTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 70, 20));

        calleInfo.setBackground(new java.awt.Color(255, 255, 255));
        calleInfo.setForeground(new java.awt.Color(0, 0, 0));
        calleInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        background.add(calleInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 250, 40));

        numeroInfo.setBackground(new java.awt.Color(255, 255, 255));
        numeroInfo.setForeground(new java.awt.Color(0, 0, 0));
        numeroInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        background.add(numeroInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 250, -1));

        codigoPostaltexto.setBackground(new java.awt.Color(6, 193, 103));
        codigoPostaltexto.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        codigoPostaltexto.setForeground(new java.awt.Color(0, 0, 0));
        codigoPostaltexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        codigoPostaltexto.setText("Codigo Postal");
        background.add(codigoPostaltexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 90, 20));

        codigoPostalInfo.setBackground(new java.awt.Color(255, 255, 255));
        codigoPostalInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        codigoPostalInfo.setForeground(new java.awt.Color(0, 0, 0));
        try {
            codigoPostalInfo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        codigoPostalInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoPostalInfoActionPerformed(evt);
            }
        });
        background.add(codigoPostalInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, 130, 40));

        ciudadTexto.setBackground(new java.awt.Color(6, 193, 103));
        ciudadTexto.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        ciudadTexto.setForeground(new java.awt.Color(0, 0, 0));
        ciudadTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ciudadTexto.setText("Ciudad");
        background.add(ciudadTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 560, 50, 20));

        ciudadInfo.setBackground(new java.awt.Color(255, 255, 255));
        ciudadInfo.setForeground(new java.awt.Color(0, 0, 0));
        ciudadInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        ciudadInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadInfoActionPerformed(evt);
            }
        });
        background.add(ciudadInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 550, 130, 40));

        tiempoEnvioTexto.setBackground(new java.awt.Color(6, 193, 103));
        tiempoEnvioTexto.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        tiempoEnvioTexto.setForeground(new java.awt.Color(0, 0, 0));
        tiempoEnvioTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tiempoEnvioTexto.setText("Tiempo Envio");
        background.add(tiempoEnvioTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 90, 20));

        textoExtra.setBackground(new java.awt.Color(6, 193, 103));
        textoExtra.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        textoExtra.setForeground(new java.awt.Color(0, 0, 0));
        textoExtra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoExtra.setText("Añada los platos 1 por 1");
        background.add(textoExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 430, 20));

        servicioCateringBox.setBackground(new java.awt.Color(255, 255, 255));
        servicioCateringBox.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        servicioCateringBox.setForeground(new java.awt.Color(0, 0, 0));
        servicioCateringBox.setSelected(true);
        servicioCateringBox.setText("Servicio Catering");
        servicioCateringBox.setBorder(null);
        servicioCateringBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        servicioCateringBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicioCateringBoxActionPerformed(evt);
            }
        });
        background.add(servicioCateringBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 120, 40));

        comidasLista.setBackground(new java.awt.Color(6, 193, 103));
        comidasLista.setFont(new java.awt.Font("Roboto Medium", 2, 12)); // NOI18N
        comidasLista.setForeground(new java.awt.Color(0, 0, 0));
        comidasLista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        comidasLista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setViewportView(comidasLista);

        background.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 440, -1));

        annadirBoton.setBackground(new java.awt.Color(6, 193, 103));
        annadirBoton.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        annadirBoton.setForeground(new java.awt.Color(0, 0, 0));
        annadirBoton.setText("AÑADIR");
        annadirBoton.setBorder(null);
        annadirBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        annadirBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                annadirBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                annadirBotonMouseExited(evt);
            }
        });
        annadirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annadirBotonActionPerformed(evt);
            }
        });
        background.add(annadirBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 181, 70));

        extraTiempoEnvioTexto.setBackground(new java.awt.Color(6, 193, 103));
        extraTiempoEnvioTexto.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        extraTiempoEnvioTexto.setForeground(new java.awt.Color(0, 0, 0));
        extraTiempoEnvioTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        extraTiempoEnvioTexto.setText("minutos");
        background.add(extraTiempoEnvioTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BarraFuncionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraFuncionesMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
        
    }//GEN-LAST:event_BarraFuncionesMousePressed

    private void BarraFuncionesMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraFuncionesMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BarraFuncionesMouseDragged

    private void exitTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextoMouseClicked
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_exitTextoMouseClicked

    private void exitTextoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextoMouseEntered
        // TODO add your handling code here:
        botonExit.setBackground(Color.red);
        exitTexto.setForeground(Color.WHITE);
    }//GEN-LAST:event_exitTextoMouseEntered

    private void exitTextoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextoMouseExited
        // TODO add your handling code here:
        botonExit.setBackground(Color.WHITE);
        exitTexto.setForeground(Color.BLACK);
    }//GEN-LAST:event_exitTextoMouseExited

    private void cerrarSesionTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionTextoMouseClicked
        // TODO add your handling code here:

        //Le advertimos de lo que va a hacer
        int respuestaUsuario = JOptionPane.showConfirmDialog(this, "¿Seguro que desea cerrar sesion?", "CERRAR SESIÓN"
            ,JOptionPane.YES_NO_OPTION );
        if(respuestaUsuario == JOptionPane.YES_OPTION)
        {
            //Le llevamos a la ventana de Inicio de sesion.
            InicioSesion cerrarSesion = new InicioSesion();
            cerrarSesion.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_cerrarSesionTextoMouseClicked

    private void cerrarSesionTextoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionTextoMouseEntered
        // TODO add your handling code here:
        cerrarSesionTexto.setForeground(Color.RED);
    }//GEN-LAST:event_cerrarSesionTextoMouseEntered

    private void cerrarSesionTextoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionTextoMouseExited
        // TODO add your handling code here:
        cerrarSesionTexto.setForeground(Color.BLACK);
    }//GEN-LAST:event_cerrarSesionTextoMouseExited

    private void atrasBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasBotonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_atrasBotonMouseClicked

    private void atrasBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasBotonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_atrasBotonMouseEntered

    private void atrasBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasBotonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_atrasBotonMouseExited

    private void atrasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBotonActionPerformed
        // TODO add your handling code here:
        ConsultaRestaurantes ventanaAnterior = new ConsultaRestaurantes();
        ventanaAnterior.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_atrasBotonActionPerformed

    private void hechoBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hechoBotonMouseEntered
        // TODO add your handling code here:
        hechoBoton.setForeground(Color.BLUE);
    }//GEN-LAST:event_hechoBotonMouseEntered

    private void hechoBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hechoBotonMouseExited
        // TODO add your handling code here:
        hechoBoton.setForeground(Color.BLACK);
    }//GEN-LAST:event_hechoBotonMouseExited

    private void hechoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hechoBotonActionPerformed
        
        //Compruebo si hay alguna casilla vacia
        if
                (
                !Sistema.esStringCorrecto(nombreInfo.getText())             ||
                !Sistema.esStringCorrecto(cifInfo.getText())                ||
                !Sistema.esStringCorrecto(especialidadInfo.getText())       ||
                !Sistema.esStringCorrecto(gastosEnvioInfo.getText())        ||
                !Sistema.esStringCorrecto(tiempoEnvioInfo.getText())        ||
                !Sistema.esStringCorrecto(calleInfo.getText())              ||
                !Sistema.esStringCorrecto(numeroInfo.getText())             ||
                !Sistema.esStringCorrecto(codigoPostalInfo.getText())       ||
                !Sistema.esStringCorrecto(ciudadInfo.getText())
                )
        {
            System.out.println("Hay alguna casilla en blanco");
        }
        //COmpruebo si se ha añadido algun plato
        else if(listaMenu.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Porfavor añada como minimo 1 plato al menu", "NO HAY MENU", JOptionPane.WARNING_MESSAGE);
        }
        else    //Si llega ha esta sentencia significa que se puede crear el restaurante, tmb se comprueba si existe
        {
            //Creamos la direccion
            Direccion direccion = new Direccion(calleInfo.getText(), numeroInfo.getText(), codigoPostalInfo.getText(), ciudadInfo.getText());
            
            //Creamos el restaurante(Todos los restaurantes empiezan con una calificacion de 5 estrellas.
            Restaurante restaurante = new Restaurante(cifInfo.getText(), nombreInfo.getText()
                    , direccion, especialidadInfo.getText(),"5.0" , gastosEnvioInfo.getText()
                    , tiempoEnvioInfo.getText(), servicioCatering, listaMenu);
            
            //Comprobamos si el restaurante existe
            if(!Sistema.existeRestaurante(cifInfo.getText(), nombreInfo.getText(), Sistema.getListaRestaurantes()))
            {
                Sistema.añadirRestaurante(restaurante);
                //Una vez añadido el restaurante lo guardamos en la "base de datos"
                Sistema.guardarDatosRestaurantes();
                
                //Le avismos de que el restaurante a sido añadido
                JOptionPane.showMessageDialog(this, "Restaurante añadido con exito", "RESTAURANTE AÑADIDO", JOptionPane.INFORMATION_MESSAGE);
                
                //Le llevamos a ver los restaurantes
                ConsultaRestaurantes ventana = new ConsultaRestaurantes();
                ventana.setVisible(true);
                this.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Este restaurante ya esta registrado", "RESTAURANTE REGISTRADO", JOptionPane.WARNING_MESSAGE);
            }
        }
        
        
    }//GEN-LAST:event_hechoBotonActionPerformed

    private void nombreInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreInfoActionPerformed

    private void gastosEnvioInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gastosEnvioInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gastosEnvioInfoActionPerformed

    private void especialidadInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidadInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especialidadInfoActionPerformed

    private void tiempoEnvioInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoEnvioInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiempoEnvioInfoActionPerformed

    private void cifInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cifInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cifInfoActionPerformed

    private void codigoPostalInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoPostalInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoPostalInfoActionPerformed

    private void ciudadInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudadInfoActionPerformed

    private void servicioCateringBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicioCateringBoxActionPerformed
        // TODO add your handling code here:
        if(servicioCateringBox.isSelected())
        {
            servicioCatering = true;
        }
        else
        {
            servicioCatering = false;
        }
    }//GEN-LAST:event_servicioCateringBoxActionPerformed

    private void annadirBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_annadirBotonMouseEntered
        // TODO add your handling code here:
        annadirBoton.setForeground(Color.BLUE);
    }//GEN-LAST:event_annadirBotonMouseEntered

    private void annadirBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_annadirBotonMouseExited
        // TODO add your handling code here:
        annadirBoton.setForeground(Color.BLACK);
    }//GEN-LAST:event_annadirBotonMouseExited

    private void annadirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annadirBotonActionPerformed
        // TODO add your handling code here:
        if(!comidasLista.isSelectionEmpty())
        {
            String comidaAñadir = comidasLista.getSelectedValue();
            String[] aux = comidaAñadir.split(",");             //Solo me interesa el primer elemento que sera el nombre
            comidaAñadir = aux[0];
            
            //Busco la comida que se quiere añadir
            int index = -1;
                for (Comida comida : Sistema.getListaComidas()) 
                {
                    index++;
                    if(comida.getNombreComida().equals(comidaAñadir))
                    {
                        Comida plato = Sistema.getComida(index);
                        if(!Sistema.esPlatoAñadido(plato))
                        {
                            listaMenu.add(plato);
                            JOptionPane.showMessageDialog(this, "Plato añadido correctamente", "INFO", JOptionPane.INFORMATION_MESSAGE);
                            break; //Para que no siga recorriendo la lista
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(this, "El plato ya esta en el menu del restaurante", "PLATO EXISTENTE", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                }
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No selecciono ningun plato", "SIN SELECCION", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_annadirBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearRestaurante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraFunciones;
    private javax.swing.JPanel FondoVerdeDerecha;
    private javax.swing.JButton annadirBoton;
    private javax.swing.JButton atrasBoton;
    private javax.swing.JPanel background;
    private javax.swing.JPanel botonExit;
    private javax.swing.JTextField calleInfo;
    private javax.swing.JLabel calleTexto;
    private javax.swing.JLabel cerrarSesionTexto;
    private javax.swing.JFormattedTextField cifInfo;
    private javax.swing.JLabel cifTexto;
    private javax.swing.JTextField ciudadInfo;
    private javax.swing.JLabel ciudadTexto;
    private javax.swing.JFormattedTextField codigoPostalInfo;
    private javax.swing.JLabel codigoPostaltexto;
    private javax.swing.JList<String> comidasLista;
    private javax.swing.JLabel crearRestauranteTexto;
    private javax.swing.JLabel direccionTexto;
    private javax.swing.JLabel eatsTexto;
    private javax.swing.JTextField especialidadInfo;
    private javax.swing.JLabel especialidadTexto;
    private javax.swing.JLabel exitTexto;
    private javax.swing.JLabel extraTiempoEnvioTexto;
    private javax.swing.JFormattedTextField gastosEnvioInfo;
    private javax.swing.JLabel gastosEnvioTexto;
    private javax.swing.JButton hechoBoton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel javaTexto;
    private javax.swing.JTextField nombreInfo;
    private javax.swing.JLabel nombreTexto;
    private javax.swing.JTextField numeroInfo;
    private javax.swing.JLabel numeroTexto;
    private javax.swing.JCheckBox servicioCateringBox;
    private javax.swing.JLabel textoExtra;
    private javax.swing.JTextField tiempoEnvioInfo;
    private javax.swing.JLabel tiempoEnvioTexto;
    // End of variables declaration//GEN-END:variables
}
