package InterfazJavaEat;

/**
 * @author David Sánchez
 */

//IMPORTES
import ClasesJavaEat.Sistema;
import java.awt.Color;
import java.io.Serializable;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;




/**
 * -Clase encargada de validar el INICO DE SESION de los usuarios REGISTRADOS
 * @author David Sanchez
 * @version 1.0
 * @since 23/05/2023
 * @see Sistema
 * @see Color
 * @see Serializable
 * @see ImageIcon
 * @see JOptionPane
 */
public class InicioSesion extends javax.swing.JFrame implements Serializable{


    int xMouse,yMouse;
    
    
    public InicioSesion() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        //Actualizamos los datos como siempre
        Sistema.cargarDatosClientes();
        Sistema.cargarDatosEmpresas();
        Sistema.cargarDatosRestaurantes();
        Sistema.cargarDatosComidas();
        Sistema.cargarDatosVentasClientes();
        Sistema.cargarDatosVentasEmpresas();
        Sistema.cargarDatosVentasCatering();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        FondoVerdeDerecha = new javax.swing.JPanel();
        javaTexto = new javax.swing.JLabel();
        eatsTexto = new javax.swing.JLabel();
        iniciarSesionTexto = new javax.swing.JLabel();
        separador1 = new javax.swing.JSeparator();
        BarraFunciones = new javax.swing.JPanel();
        botonExit = new javax.swing.JPanel();
        exitTexto = new javax.swing.JLabel();
        usuarioTexto = new javax.swing.JLabel();
        contraseñaTexto = new javax.swing.JLabel();
        separador2 = new javax.swing.JSeparator();
        usuarioInfo = new javax.swing.JTextField();
        contraseñaInfo = new javax.swing.JPasswordField();
        entrarBoton = new javax.swing.JButton();
        registrarseBoton = new javax.swing.JLabel();
        mostrarContraseñaBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoVerdeDerecha.setBackground(new java.awt.Color(6, 193, 103));

        javaTexto.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        javaTexto.setForeground(new java.awt.Color(0, 0, 0));
        javaTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        javaTexto.setText("JAVA");

        eatsTexto.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        eatsTexto.setForeground(new java.awt.Color(0, 0, 0));
        eatsTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eatsTexto.setText("EATS");

        javax.swing.GroupLayout FondoVerdeDerechaLayout = new javax.swing.GroupLayout(FondoVerdeDerecha);
        FondoVerdeDerecha.setLayout(FondoVerdeDerechaLayout);
        FondoVerdeDerechaLayout.setHorizontalGroup(
            FondoVerdeDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eatsTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
            .addComponent(javaTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FondoVerdeDerechaLayout.setVerticalGroup(
            FondoVerdeDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoVerdeDerechaLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(javaTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eatsTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
        );

        background.add(FondoVerdeDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 260, 550));

        iniciarSesionTexto.setBackground(new java.awt.Color(6, 193, 103));
        iniciarSesionTexto.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        iniciarSesionTexto.setForeground(new java.awt.Color(0, 0, 0));
        iniciarSesionTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        iniciarSesionTexto.setText("INICIAR SESIÓN");
        background.add(iniciarSesionTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 440, 60));

        separador1.setBackground(new java.awt.Color(0, 0, 0));
        separador1.setFont(new java.awt.Font("sansserif", 0, 40));
        background.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 500, 10));

        BarraFunciones.setBackground(new java.awt.Color(255, 255, 255));
        BarraFunciones.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraFuncionesMouseDragged(evt);
            }
        });
        BarraFunciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraFuncionesMousePressed(evt);
            }
        });

        botonExit.setBackground(new java.awt.Color(255, 255, 255));

        exitTexto.setBackground(new java.awt.Color(255, 255, 255));
        exitTexto.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        exitTexto.setForeground(new java.awt.Color(0, 0, 0));
        exitTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTexto.setText("X");
        exitTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTextoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTextoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTextoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botonExitLayout = new javax.swing.GroupLayout(botonExit);
        botonExit.setLayout(botonExitLayout);
        botonExitLayout.setHorizontalGroup(
            botonExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        botonExitLayout.setVerticalGroup(
            botonExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BarraFuncionesLayout = new javax.swing.GroupLayout(BarraFunciones);
        BarraFunciones.setLayout(BarraFuncionesLayout);
        BarraFuncionesLayout.setHorizontalGroup(
            BarraFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraFuncionesLayout.createSequentialGroup()
                .addComponent(botonExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 859, Short.MAX_VALUE))
        );
        BarraFuncionesLayout.setVerticalGroup(
            BarraFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraFuncionesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(BarraFunciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        usuarioTexto.setFont(new java.awt.Font("Roboto Medium", 3, 24)); // NOI18N
        usuarioTexto.setForeground(new java.awt.Color(0, 0, 0));
        usuarioTexto.setText("Correo");
        background.add(usuarioTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 260, 60));

        contraseñaTexto.setFont(new java.awt.Font("Roboto Medium", 3, 24)); // NOI18N
        contraseñaTexto.setForeground(new java.awt.Color(0, 0, 0));
        contraseñaTexto.setText("Contraseña");
        background.add(contraseñaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 260, 60));

        separador2.setBackground(new java.awt.Color(0, 0, 0));
        separador2.setFont(new java.awt.Font("sansserif", 0, 40));
        background.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 500, 10));

        usuarioInfo.setBackground(new java.awt.Color(255, 255, 255));
        usuarioInfo.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        usuarioInfo.setForeground(new java.awt.Color(153, 153, 153));
        usuarioInfo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        usuarioInfo.setText("Ingrese su correo electronico");
        usuarioInfo.setBorder(null);
        usuarioInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usuarioInfoMousePressed(evt);
            }
        });
        usuarioInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioInfoActionPerformed(evt);
            }
        });
        background.add(usuarioInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 500, 30));

        contraseñaInfo.setBackground(new java.awt.Color(255, 255, 255));
        contraseñaInfo.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        contraseñaInfo.setForeground(new java.awt.Color(153, 153, 153));
        contraseñaInfo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        contraseñaInfo.setText("********");
        contraseñaInfo.setBorder(null);
        contraseñaInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contraseñaInfoMousePressed(evt);
            }
        });
        contraseñaInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaInfoActionPerformed(evt);
            }
        });
        background.add(contraseñaInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 326, 500, 20));

        entrarBoton.setBackground(new java.awt.Color(6, 193, 103));
        entrarBoton.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        entrarBoton.setForeground(new java.awt.Color(0, 0, 0));
        entrarBoton.setText("ENTRAR");
        entrarBoton.setBorder(null);
        entrarBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entrarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entrarBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                entrarBotonMouseExited(evt);
            }
        });
        entrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarBotonActionPerformed(evt);
            }
        });
        background.add(entrarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 160, 70));

        registrarseBoton.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        registrarseBoton.setForeground(new java.awt.Color(0, 0, 0));
        registrarseBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrarseBoton.setText("¿No tienes una cuenta?");
        registrarseBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarseBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarseBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrarseBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrarseBotonMouseExited(evt);
            }
        });
        background.add(registrarseBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 280, 50));

        mostrarContraseñaBox.setBackground(new java.awt.Color(255, 255, 255));
        mostrarContraseñaBox.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        mostrarContraseñaBox.setForeground(new java.awt.Color(0, 0, 0));
        mostrarContraseñaBox.setText("Mostrar contraseña");
        mostrarContraseñaBox.setBorder(null);
        mostrarContraseñaBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostrarContraseñaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarContraseñaBoxActionPerformed(evt);
            }
        });
        background.add(mostrarContraseñaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarBotonActionPerformed
        // TODO add your handling code here:
        if(usuarioInfo.getText().equals("admin@javaeat.com")&& String.valueOf(contraseñaInfo.getPassword()).equals("admin")) //Inicio de admin
        {
            JOptionPane.showMessageDialog(this, "Iniciando sesion como administrador", "ADMIN"
                    , JOptionPane.WARNING_MESSAGE);
            
            InicioAdmin ventanaAdmin = new InicioAdmin();
            ventanaAdmin.setVisible(true);
            this.setVisible(false);
        }
        else if(Sistema.existeCliente(usuarioInfo.getText(), String.valueOf(contraseñaInfo.getPassword())
                , Sistema.getListaClientes()))//Incio de cliente
        {
            //Actualizamos el cliente que se esta logeando en la interfaz
            Sistema.actualizarClienteActual(usuarioInfo.getText(), String.valueOf(contraseñaInfo.getPassword())
                    , Sistema.getListaClientes());
            
            //Le mandamos a su respectiva interfaz
            InicioCliente ventanaIncio = new InicioCliente();
            ventanaIncio.setVisible(true);
            this.setVisible(false);
        }
        else if(Sistema.existeEmpresa(usuarioInfo.getText(), String.valueOf(contraseñaInfo.getPassword())
                , Sistema.getListaEmpresas()))//Inicio de empresa
        {
            //Actualizamos la empresa que se esta logeando en la interfaz
            Sistema.actualizarEmpresaActual(usuarioInfo.getText(), String.valueOf(contraseñaInfo.getPassword())
                    , Sistema.getListaEmpresas());
            
            //Le mandamos a su respectiva interfaz
            InicioEmpresa ventanaIncio = new InicioEmpresa();
            ventanaIncio.setVisible(true);
            this.setVisible(false);
        }
        else    //Si ocurre esta sentencia significa que la cuenta no existe o que las credenciales estan mal
        {
            JOptionPane.showMessageDialog(this, "Asegurese de introducir bien los datos y tener la cuenta registrada.", "¿Cuenta Inexistente?", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_entrarBotonActionPerformed

    private void BarraFuncionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraFuncionesMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
        
    }//GEN-LAST:event_BarraFuncionesMousePressed

    private void BarraFuncionesMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraFuncionesMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BarraFuncionesMouseDragged

    private void exitTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextoMouseClicked
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_exitTextoMouseClicked

    private void exitTextoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextoMouseEntered
        // TODO add your handling code here:
        botonExit.setBackground(Color.red);
        exitTexto.setForeground(Color.WHITE);
    }//GEN-LAST:event_exitTextoMouseEntered

    private void exitTextoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextoMouseExited
        // TODO add your handling code here:
        botonExit.setBackground(Color.WHITE);
        exitTexto.setForeground(Color.BLACK);
    }//GEN-LAST:event_exitTextoMouseExited

    private void entrarBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarBotonMouseEntered
        // TODO add your handling code here:
        entrarBoton.setForeground(Color.BLUE);
        
    }//GEN-LAST:event_entrarBotonMouseEntered

    private void entrarBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarBotonMouseExited
        // TODO add your handling code here:
        entrarBoton.setForeground(Color.BLACK);
    }//GEN-LAST:event_entrarBotonMouseExited

    private void registrarseBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarseBotonMouseEntered
        // TODO add your handling code here:
        registrarseBoton.setForeground(Color.BLUE);
    }//GEN-LAST:event_registrarseBotonMouseEntered

    private void registrarseBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarseBotonMouseExited
        // TODO add your handling code here:
        registrarseBoton.setForeground(Color.BLACK);
    }//GEN-LAST:event_registrarseBotonMouseExited

    private void usuarioInfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioInfoMousePressed
        // TODO add your handling code here:
        if(usuarioInfo.getText().equals("Ingrese su correo electronico"))
        {
            usuarioInfo.setText("");
            usuarioInfo.setForeground(Color.BLACK);
        
        }
        if(String.valueOf(contraseñaInfo.getPassword()).isEmpty())
        {
            contraseñaInfo.setText("********");
            contraseñaInfo.setForeground(Color.GRAY);
        }
        
    }//GEN-LAST:event_usuarioInfoMousePressed

    private void contraseñaInfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraseñaInfoMousePressed
        // TODO add your handling code here:
        if(String.valueOf(contraseñaInfo.getPassword()).equals("********"))
        {
            contraseñaInfo.setText("");
            contraseñaInfo.setForeground(Color.BLACK);
        }
        if(usuarioInfo.getText().isEmpty())
        {
            usuarioInfo.setText("Ingrese su correo electronico");
            usuarioInfo.setForeground(Color.GRAY);
        }
        
        
    }//GEN-LAST:event_contraseñaInfoMousePressed

    private void contraseñaInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaInfoActionPerformed

    private void registrarseBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarseBotonMouseClicked
        // TODO add your handling code here:
        
        Registro ventanaRegistro = new Registro();
        ventanaRegistro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registrarseBotonMouseClicked

    private void usuarioInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioInfoActionPerformed

    private void mostrarContraseñaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarContraseñaBoxActionPerformed
        // TODO add your handling code here:
        if(mostrarContraseñaBox.isSelected())
        {
            contraseñaInfo.setEchoChar((char)0);
        }
        else
        {
            contraseñaInfo.setEchoChar('*');
        }
    }//GEN-LAST:event_mostrarContraseñaBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraFunciones;
    private javax.swing.JPanel FondoVerdeDerecha;
    private javax.swing.JPanel background;
    private javax.swing.JPanel botonExit;
    private javax.swing.JPasswordField contraseñaInfo;
    private javax.swing.JLabel contraseñaTexto;
    private javax.swing.JLabel eatsTexto;
    private javax.swing.JButton entrarBoton;
    private javax.swing.JLabel exitTexto;
    private javax.swing.JLabel iniciarSesionTexto;
    private javax.swing.JLabel javaTexto;
    private javax.swing.JCheckBox mostrarContraseñaBox;
    private javax.swing.JLabel registrarseBoton;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JTextField usuarioInfo;
    private javax.swing.JLabel usuarioTexto;
    // End of variables declaration//GEN-END:variables
}
