package InterfazJavaEat;

/**
 * @author David Sánchez
 */


//IMPORTES
import ClasesJavaEat.Comida;
import ClasesJavaEat.Restaurante;
import ClasesJavaEat.Sistema;
import java.awt.Color;
import java.io.Serializable;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;




/**
 * -Clase encargada de mostrar una lista de {@link Restaurante} y otra de {@link Comida} ademas de poder eliminar y añadir cada uno de ellos.
 * @author David Sanchez
 * @version 1.0
 * @since 23/05/2023
 * @see Comida
 * @see Restaurante
 * @see Sistema
 * @see Color
 * @see Serializable
 * @see DefaultListModel
 * @see ImageIcon
 * @see JOptionPane
 */
public class ConsultaRestaurantes extends javax.swing.JFrame implements Serializable{

    
    int xMouse,yMouse;
    DefaultListModel modeloComidas = new DefaultListModel();           //Creamos un modelo para comidasLista(JList)
    DefaultListModel modeloRestaurantes = new DefaultListModel();           //Creamos un modelo para restaurantesLista(JList)
    
    
    public ConsultaRestaurantes() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        //Actualizamos los datos como siempre
        Sistema.cargarDatosClientes();
        Sistema.cargarDatosEmpresas();
        Sistema.cargarDatosRestaurantes();
        Sistema.cargarDatosComidas();
        Sistema.cargarDatosVentasClientes();
        Sistema.cargarDatosVentasEmpresas();
        Sistema.cargarDatosVentasCatering();
        
        //Le damos un modelo a usuariosLista(JList) y a restaurantesLista(JList)
        comidasLista.setModel(modeloComidas);
        restaurantesLista.setModel(modeloRestaurantes);
        
        //Quitamos todos los datos que haya en las dos listas (Para poner los actalizados)
        modeloComidas.removeAllElements();
        modeloRestaurantes.removeAllElements();
        
        /*
        Añadimos primero todas las comidas(Se puede hacer todo en una sola linea de codigo para ahorrar espacio 
        en memoria pero se a optado por obtener mejor claridad).
        */
        for(Comida comida : Sistema.getListaComidas())
        
        {
            String nombre = comida.getNombreComida();
            String ingredientes = comida.getIngredientes().toString();
            String precio = comida.getPrecio();

            String txt = nombre+", ("+precio+"€)"+"    Contiene los ingredientes"+ingredientes+".";
            modeloComidas.addElement(txt);
        }
        
        /*
        Añadimos ahora todos los restaurantes(Se puede hacer todo en una sola linea de codigo para ahorrar espacio 
        en memoria pero se a optado por obtener mejor claridad).
        */
        for (Restaurante restaurante : Sistema.getListaRestaurantes()) 
        {
            
            String cif = restaurante.getCif();
            String nombre = restaurante.getNombre();
            String especialidad = restaurante.getEspecialidad();
            String calificacion = restaurante.getCalificacion();

            String txt = cif+", perteneciente al restaurante: "+nombre
                    +" con especialidad en "+especialidad+" tiene una calificacion media de "+calificacion+" puntos.";
            
            modeloRestaurantes.addElement(txt);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        FondoVerdeDerecha = new javax.swing.JPanel();
        eatsTexto = new javax.swing.JLabel();
        cerrarSesionTexto = new javax.swing.JLabel();
        atrasBoton = new javax.swing.JButton();
        crearComidaBoton = new javax.swing.JButton();
        crearRestauranteBoton = new javax.swing.JButton();
        javaTexto = new javax.swing.JLabel();
        BarraFunciones = new javax.swing.JPanel();
        botonExit = new javax.swing.JPanel();
        exitTexto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        eliminarComidaBoton = new javax.swing.JButton();
        restaurantesTexto = new javax.swing.JLabel();
        comidasTexto = new javax.swing.JLabel();
        eliminarRestauranteBoton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        restaurantesLista = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        comidasLista = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoVerdeDerecha.setBackground(new java.awt.Color(6, 193, 103));

        eatsTexto.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        eatsTexto.setForeground(new java.awt.Color(0, 0, 0));
        eatsTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eatsTexto.setText("EATS");

        cerrarSesionTexto.setBackground(new java.awt.Color(255, 255, 255));
        cerrarSesionTexto.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        cerrarSesionTexto.setForeground(new java.awt.Color(0, 0, 0));
        cerrarSesionTexto.setText("Cerrar Sesión");
        cerrarSesionTexto.setBorder(null);
        cerrarSesionTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrarSesionTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarSesionTextoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarSesionTextoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarSesionTextoMouseExited(evt);
            }
        });

        atrasBoton.setBackground(new java.awt.Color(6, 193, 103));
        atrasBoton.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        atrasBoton.setForeground(new java.awt.Color(0, 0, 0));
        atrasBoton.setBorder(null);
        atrasBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atrasBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atrasBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atrasBotonMouseExited(evt);
            }
        });
        atrasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBotonActionPerformed(evt);
            }
        });

        crearComidaBoton.setBackground(new java.awt.Color(6, 193, 103));
        crearComidaBoton.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        crearComidaBoton.setForeground(new java.awt.Color(0, 0, 0));
        crearComidaBoton.setText("Crear Comida");
        crearComidaBoton.setBorder(null);
        crearComidaBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearComidaBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                crearComidaBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                crearComidaBotonMouseExited(evt);
            }
        });
        crearComidaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearComidaBotonActionPerformed(evt);
            }
        });

        crearRestauranteBoton.setBackground(new java.awt.Color(6, 193, 103));
        crearRestauranteBoton.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        crearRestauranteBoton.setForeground(new java.awt.Color(0, 0, 0));
        crearRestauranteBoton.setText("Crear Restaurante");
        crearRestauranteBoton.setBorder(null);
        crearRestauranteBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearRestauranteBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                crearRestauranteBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                crearRestauranteBotonMouseExited(evt);
            }
        });
        crearRestauranteBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearRestauranteBotonActionPerformed(evt);
            }
        });

        javaTexto.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        javaTexto.setForeground(new java.awt.Color(0, 0, 0));
        javaTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        javaTexto.setText("JAVA");

        javax.swing.GroupLayout FondoVerdeDerechaLayout = new javax.swing.GroupLayout(FondoVerdeDerecha);
        FondoVerdeDerecha.setLayout(FondoVerdeDerechaLayout);
        FondoVerdeDerechaLayout.setHorizontalGroup(
            FondoVerdeDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoVerdeDerechaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(atrasBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(FondoVerdeDerechaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FondoVerdeDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eatsTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(FondoVerdeDerechaLayout.createSequentialGroup()
                        .addComponent(javaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoVerdeDerechaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(FondoVerdeDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crearComidaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(FondoVerdeDerechaLayout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(cerrarSesionTexto)
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoVerdeDerechaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(crearRestauranteBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        FondoVerdeDerechaLayout.setVerticalGroup(
            FondoVerdeDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoVerdeDerechaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cerrarSesionTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(crearRestauranteBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(javaTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eatsTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(crearComidaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(atrasBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        atrasBoton.setIcon(new ImageIcon("Imagenes/logoAtras.png"));

        background.add(FondoVerdeDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 270, 550));

        BarraFunciones.setBackground(new java.awt.Color(255, 255, 255));
        BarraFunciones.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraFuncionesMouseDragged(evt);
            }
        });
        BarraFunciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraFuncionesMousePressed(evt);
            }
        });

        botonExit.setBackground(new java.awt.Color(255, 255, 255));

        exitTexto.setBackground(new java.awt.Color(255, 255, 255));
        exitTexto.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        exitTexto.setForeground(new java.awt.Color(0, 0, 0));
        exitTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTexto.setText("X");
        exitTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTextoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTextoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTextoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botonExitLayout = new javax.swing.GroupLayout(botonExit);
        botonExit.setLayout(botonExitLayout);
        botonExitLayout.setHorizontalGroup(
            botonExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        botonExitLayout.setVerticalGroup(
            botonExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BarraFuncionesLayout = new javax.swing.GroupLayout(BarraFunciones);
        BarraFunciones.setLayout(BarraFuncionesLayout);
        BarraFuncionesLayout.setHorizontalGroup(
            BarraFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraFuncionesLayout.createSequentialGroup()
                .addComponent(botonExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        BarraFuncionesLayout.setVerticalGroup(
            BarraFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraFuncionesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(BarraFunciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 640, 20));

        eliminarComidaBoton.setBackground(new java.awt.Color(6, 193, 103));
        eliminarComidaBoton.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        eliminarComidaBoton.setForeground(new java.awt.Color(0, 0, 0));
        eliminarComidaBoton.setText("Eliminar");
        eliminarComidaBoton.setBorder(null);
        eliminarComidaBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarComidaBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminarComidaBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminarComidaBotonMouseExited(evt);
            }
        });
        eliminarComidaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarComidaBotonActionPerformed(evt);
            }
        });
        background.add(eliminarComidaBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 160, 70));

        restaurantesTexto.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        restaurantesTexto.setForeground(new java.awt.Color(0, 0, 0));
        restaurantesTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        restaurantesTexto.setText("Informacion relevante restaurantes");
        background.add(restaurantesTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 430, -1));

        comidasTexto.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        comidasTexto.setForeground(new java.awt.Color(0, 0, 0));
        comidasTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        comidasTexto.setText("Informacion relevante comidas");
        background.add(comidasTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 440, -1));

        eliminarRestauranteBoton.setBackground(new java.awt.Color(6, 193, 103));
        eliminarRestauranteBoton.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        eliminarRestauranteBoton.setForeground(new java.awt.Color(0, 0, 0));
        eliminarRestauranteBoton.setText("Eliminar");
        eliminarRestauranteBoton.setBorder(null);
        eliminarRestauranteBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarRestauranteBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminarRestauranteBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminarRestauranteBotonMouseExited(evt);
            }
        });
        eliminarRestauranteBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarRestauranteBotonActionPerformed(evt);
            }
        });
        background.add(eliminarRestauranteBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 160, 70));

        restaurantesLista.setBackground(new java.awt.Color(6, 193, 103));
        restaurantesLista.setFont(new java.awt.Font("Roboto Medium", 2, 12)); // NOI18N
        restaurantesLista.setForeground(new java.awt.Color(0, 0, 0));
        restaurantesLista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        restaurantesLista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(restaurantesLista);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 440, -1));

        comidasLista.setBackground(new java.awt.Color(6, 193, 103));
        comidasLista.setFont(new java.awt.Font("Roboto Medium", 2, 12)); // NOI18N
        comidasLista.setForeground(new java.awt.Color(0, 0, 0));
        comidasLista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        comidasLista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setViewportView(comidasLista);

        background.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 440, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BarraFuncionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraFuncionesMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
        
    }//GEN-LAST:event_BarraFuncionesMousePressed

    private void BarraFuncionesMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraFuncionesMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BarraFuncionesMouseDragged

    private void exitTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextoMouseClicked
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_exitTextoMouseClicked

    private void exitTextoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextoMouseEntered
        // TODO add your handling code here:
        botonExit.setBackground(Color.red);
        exitTexto.setForeground(Color.WHITE);
    }//GEN-LAST:event_exitTextoMouseEntered

    private void exitTextoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextoMouseExited
        // TODO add your handling code here:
        botonExit.setBackground(Color.WHITE);
        exitTexto.setForeground(Color.BLACK);
    }//GEN-LAST:event_exitTextoMouseExited

    private void cerrarSesionTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionTextoMouseClicked
        // TODO add your handling code here:

        //Le advertimos de lo que va a hacer
        int respuestaUsuario = JOptionPane.showConfirmDialog(this, "¿Seguro que desea cerrar sesion?", "CERRAR SESIÓN"
            ,JOptionPane.YES_NO_OPTION );
        if(respuestaUsuario == JOptionPane.YES_OPTION)
        {
            //Le llevamos a la ventana de Inicio de sesion.
            InicioSesion cerrarSesion = new InicioSesion();
            cerrarSesion.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_cerrarSesionTextoMouseClicked

    private void cerrarSesionTextoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionTextoMouseEntered
        // TODO add your handling code here:
        cerrarSesionTexto.setForeground(Color.RED);
    }//GEN-LAST:event_cerrarSesionTextoMouseEntered

    private void cerrarSesionTextoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionTextoMouseExited
        // TODO add your handling code here:
        cerrarSesionTexto.setForeground(Color.BLACK);
    }//GEN-LAST:event_cerrarSesionTextoMouseExited

    private void atrasBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasBotonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_atrasBotonMouseClicked

    private void atrasBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasBotonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_atrasBotonMouseEntered

    private void atrasBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasBotonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_atrasBotonMouseExited

    private void atrasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBotonActionPerformed
        // TODO add your handling code here:
        InicioAdmin ventanaAnterior = new InicioAdmin();
        ventanaAnterior.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_atrasBotonActionPerformed

    private void crearRestauranteBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearRestauranteBotonMouseEntered
        // TODO add your handling code here:
        crearRestauranteBoton.setForeground(Color.BLUE);
    }//GEN-LAST:event_crearRestauranteBotonMouseEntered

    private void crearRestauranteBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearRestauranteBotonMouseExited
        // TODO add your handling code here:
        crearRestauranteBoton.setForeground(Color.BLACK);
    }//GEN-LAST:event_crearRestauranteBotonMouseExited

    private void crearRestauranteBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearRestauranteBotonActionPerformed
        // TODO add your handling code here:
        CrearRestaurante ventana = new CrearRestaurante();
        ventana.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_crearRestauranteBotonActionPerformed

    private void eliminarComidaBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarComidaBotonMouseEntered
        // TODO add your handling code here:
        eliminarComidaBoton.setForeground(Color.red);
    }//GEN-LAST:event_eliminarComidaBotonMouseEntered

    private void eliminarComidaBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarComidaBotonMouseExited
        // TODO add your handling code here:
        eliminarComidaBoton.setForeground(Color.BLACK);
    }//GEN-LAST:event_eliminarComidaBotonMouseExited

    private void eliminarComidaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarComidaBotonActionPerformed
        
        //Le advertimos de lo que va a hacer  
        if(!comidasLista.isSelectionEmpty())
        {
            int respuestaUsuario = JOptionPane.showConfirmDialog(this, "¿Seguro que quieres eliminar esta comida?", "ELIMINAR COMIDA"
            ,JOptionPane.YES_NO_OPTION );
        
            if(respuestaUsuario == JOptionPane.YES_OPTION)
            {

                String comidaEliminar = comidasLista.getSelectedValue();
                String[] aux = comidaEliminar.split(",");             //Solo me interesa el primer elemento que sera el nombre
                comidaEliminar = aux[0];

                //Busco la comida que se quiere eliminar
                int index = -1;
                for (Comida comida : Sistema.getListaComidas()) 
                {
                    index++;
                    if(comida.getNombreComida().equals(comidaEliminar))
                    {
                        Sistema.eliminarComida(index);
                        JOptionPane.showMessageDialog(this, "Comida eliminada con exito", "INFO", JOptionPane.INFORMATION_MESSAGE);
                        break; //Para que no siga recorriendo la lista
                    }
                }

                //Guardo los datos
                Sistema.guardarDatosComidas();

                //Actualizo la pagina
                ConsultaRestaurantes reinicio = new ConsultaRestaurantes();
                reinicio.setVisible(true);
                this.setVisible(false);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No selecciono ninguna comida", "SIN SELECCION", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_eliminarComidaBotonActionPerformed

    private void crearComidaBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearComidaBotonMouseEntered
        // TODO add your handling code here:
        crearComidaBoton.setForeground(Color.BLUE);
    }//GEN-LAST:event_crearComidaBotonMouseEntered

    private void crearComidaBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearComidaBotonMouseExited
        // TODO add your handling code here:
        crearComidaBoton.setForeground(Color.BLACK);
    }//GEN-LAST:event_crearComidaBotonMouseExited

    private void crearComidaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearComidaBotonActionPerformed
        // TODO add your handling code here:
        CrearComida ventana = new CrearComida();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_crearComidaBotonActionPerformed

    private void eliminarRestauranteBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarRestauranteBotonMouseEntered
        // TODO add your handling code here:
        eliminarRestauranteBoton.setForeground(Color.red);
    }//GEN-LAST:event_eliminarRestauranteBotonMouseEntered

    private void eliminarRestauranteBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarRestauranteBotonMouseExited
        // TODO add your handling code here:
        eliminarRestauranteBoton.setForeground(Color.BLACK);
    }//GEN-LAST:event_eliminarRestauranteBotonMouseExited

    private void eliminarRestauranteBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarRestauranteBotonActionPerformed
        // TODO add your handling code here:
        if(!restaurantesLista.isSelectionEmpty())
        {
            int respuestaUsuario = JOptionPane.showConfirmDialog(this, "¿Seguro que quieres eliminar este restaurante?", "ELIMINAR RESTAURANTE"
            ,JOptionPane.YES_NO_OPTION );
        
            if(respuestaUsuario == JOptionPane.YES_OPTION)
            {

                String restauranteEliminar = restaurantesLista.getSelectedValue();
                String[] aux = restauranteEliminar.split(",");             //Solo me interesa el primer elemento que sera el nombre
                restauranteEliminar = aux[0];

                //Busco el restaurante que se quiere eliminar
                int index = -1;
                for (Restaurante restaurante : Sistema.getListaRestaurantes()) 
                {
                    index++;
                    if(restaurante.getCif().equals(restauranteEliminar))
                    {
                        Sistema.eliminarRestaurante(index);
                        JOptionPane.showMessageDialog(this, "Restaurante eliminado con exito", "INFO", JOptionPane.INFORMATION_MESSAGE);
                        break; //Para que no siga recorriendo la lista
                    }
                }

                //Guardo los datos
                Sistema.guardarDatosRestaurantes();

                //Actualizo la pagina
                ConsultaRestaurantes reinicio = new ConsultaRestaurantes();
                reinicio.setVisible(true);
                this.setVisible(false);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No selecciono ninguna restaurante", "SIN SELECCION", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_eliminarRestauranteBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaRestaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaRestaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaRestaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaRestaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaRestaurantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraFunciones;
    private javax.swing.JPanel FondoVerdeDerecha;
    private javax.swing.JButton atrasBoton;
    private javax.swing.JPanel background;
    private javax.swing.JPanel botonExit;
    private javax.swing.JLabel cerrarSesionTexto;
    private javax.swing.JList<String> comidasLista;
    private javax.swing.JLabel comidasTexto;
    private javax.swing.JButton crearComidaBoton;
    private javax.swing.JButton crearRestauranteBoton;
    private javax.swing.JLabel eatsTexto;
    private javax.swing.JButton eliminarComidaBoton;
    private javax.swing.JButton eliminarRestauranteBoton;
    private javax.swing.JLabel exitTexto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel javaTexto;
    private javax.swing.JList<String> restaurantesLista;
    private javax.swing.JLabel restaurantesTexto;
    // End of variables declaration//GEN-END:variables
}
