package InterfazJavaEat;

/**
 * @author David Sánchez
 */


//IMPORTES
import ClasesJavaEat.Comida;
import ClasesJavaEat.Sistema;
import ClasesJavaEat.ImageFilter;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;




/**
 * -Clase encargada de crear una {@link Comida}
 * @author David Sanchez
 * @version 1.0
 * @since 23/05/2023
 * @see Comida
 * @see Sistema
 * @see ImageFilter
 * @see Color
 * @see BufferedImage
 * @see File
 * @see IOException
 * @see Serializable
 * @see ArrayList
 * @see ImageIO
 * @see ImageIcon
 * @see JFileChooser
 * @see JOptionPane
 */
public class CrearComida extends javax.swing.JFrame implements Serializable{

    
    int xMouse,yMouse;
    private String nombreImagen, rutaImagen, extension = "jpg";
    private File file;
    private BufferedImage bimage;
    private  ArrayList<String> listaIngredientes = new ArrayList<>();

    
    
    public CrearComida() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        //Actualizamos los datos como siempre
        Sistema.cargarDatosClientes();
        Sistema.cargarDatosEmpresas();
        Sistema.cargarDatosRestaurantes();
        Sistema.cargarDatosComidas();
        Sistema.cargarDatosVentasClientes();
        Sistema.cargarDatosVentasEmpresas();
        Sistema.cargarDatosVentasCatering();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        FondoVerdeDerecha = new javax.swing.JPanel();
        javaTexto = new javax.swing.JLabel();
        eatsTexto = new javax.swing.JLabel();
        cerrarSesionTexto = new javax.swing.JLabel();
        atrasBoton = new javax.swing.JButton();
        hechoBoton = new javax.swing.JButton();
        BarraFunciones = new javax.swing.JPanel();
        botonExit = new javax.swing.JPanel();
        exitTexto = new javax.swing.JLabel();
        nombreTexto = new javax.swing.JLabel();
        nombreInfo = new javax.swing.JTextField();
        precioInfo = new javax.swing.JFormattedTextField();
        crearComidaTexto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        precioTExto = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        ingredientesTexto = new javax.swing.JLabel();
        imagenTexto = new javax.swing.JLabel();
        ingredientesInfo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        elegirImagenBoton = new javax.swing.JButton();
        borrarImagen = new javax.swing.JButton();
        annadirIngredienteBoton = new javax.swing.JButton();
        jLabelImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoVerdeDerecha.setBackground(new java.awt.Color(6, 193, 103));

        javaTexto.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        javaTexto.setForeground(new java.awt.Color(0, 0, 0));
        javaTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        javaTexto.setText("JAVA");

        eatsTexto.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        eatsTexto.setForeground(new java.awt.Color(0, 0, 0));
        eatsTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eatsTexto.setText("EATS");

        cerrarSesionTexto.setBackground(new java.awt.Color(255, 255, 255));
        cerrarSesionTexto.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        cerrarSesionTexto.setForeground(new java.awt.Color(0, 0, 0));
        cerrarSesionTexto.setText("Cerrar Sesión");
        cerrarSesionTexto.setBorder(null);
        cerrarSesionTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrarSesionTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarSesionTextoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarSesionTextoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarSesionTextoMouseExited(evt);
            }
        });

        atrasBoton.setBackground(new java.awt.Color(6, 193, 103));
        atrasBoton.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        atrasBoton.setForeground(new java.awt.Color(0, 0, 0));
        atrasBoton.setBorder(null);
        atrasBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atrasBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atrasBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atrasBotonMouseExited(evt);
            }
        });
        atrasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBotonActionPerformed(evt);
            }
        });

        hechoBoton.setBackground(new java.awt.Color(6, 193, 103));
        hechoBoton.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        hechoBoton.setForeground(new java.awt.Color(0, 0, 0));
        hechoBoton.setText("¡HECHO!");
        hechoBoton.setBorder(null);
        hechoBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hechoBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hechoBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hechoBotonMouseExited(evt);
            }
        });
        hechoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hechoBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoVerdeDerechaLayout = new javax.swing.GroupLayout(FondoVerdeDerecha);
        FondoVerdeDerecha.setLayout(FondoVerdeDerechaLayout);
        FondoVerdeDerechaLayout.setHorizontalGroup(
            FondoVerdeDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eatsTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
            .addComponent(javaTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoVerdeDerechaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(atrasBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoVerdeDerechaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrarSesionTexto)
                .addContainerGap())
            .addGroup(FondoVerdeDerechaLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(hechoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FondoVerdeDerechaLayout.setVerticalGroup(
            FondoVerdeDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoVerdeDerechaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cerrarSesionTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(javaTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eatsTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196)
                .addComponent(hechoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(atrasBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        atrasBoton.setIcon(new ImageIcon("Imagenes/logoAtras.png"));

        background.add(FondoVerdeDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 280, 750));

        BarraFunciones.setBackground(new java.awt.Color(255, 255, 255));
        BarraFunciones.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraFuncionesMouseDragged(evt);
            }
        });
        BarraFunciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraFuncionesMousePressed(evt);
            }
        });

        botonExit.setBackground(new java.awt.Color(255, 255, 255));

        exitTexto.setBackground(new java.awt.Color(255, 255, 255));
        exitTexto.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        exitTexto.setForeground(new java.awt.Color(0, 0, 0));
        exitTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTexto.setText("X");
        exitTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTextoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTextoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTextoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botonExitLayout = new javax.swing.GroupLayout(botonExit);
        botonExit.setLayout(botonExitLayout);
        botonExitLayout.setHorizontalGroup(
            botonExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        botonExitLayout.setVerticalGroup(
            botonExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BarraFuncionesLayout = new javax.swing.GroupLayout(BarraFunciones);
        BarraFunciones.setLayout(BarraFuncionesLayout);
        BarraFuncionesLayout.setHorizontalGroup(
            BarraFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraFuncionesLayout.createSequentialGroup()
                .addComponent(botonExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        BarraFuncionesLayout.setVerticalGroup(
            BarraFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraFuncionesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(BarraFunciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        nombreTexto.setBackground(new java.awt.Color(6, 193, 103));
        nombreTexto.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        nombreTexto.setForeground(new java.awt.Color(0, 0, 0));
        nombreTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nombreTexto.setText("Nombre ");
        background.add(nombreTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 60, 20));

        nombreInfo.setBackground(new java.awt.Color(255, 255, 255));
        nombreInfo.setForeground(new java.awt.Color(0, 0, 0));
        nombreInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        nombreInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreInfoActionPerformed(evt);
            }
        });
        background.add(nombreInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 260, 40));

        precioInfo.setBackground(new java.awt.Color(255, 255, 255));
        precioInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        precioInfo.setForeground(new java.awt.Color(0, 0, 0));
        try {
            precioInfo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        precioInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioInfoActionPerformed(evt);
            }
        });
        background.add(precioInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 130, 40));

        crearComidaTexto.setBackground(new java.awt.Color(6, 193, 103));
        crearComidaTexto.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        crearComidaTexto.setForeground(new java.awt.Color(0, 0, 0));
        crearComidaTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        crearComidaTexto.setText("Crear comida");
        background.add(crearComidaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 440, 60));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 450, 20));

        precioTExto.setBackground(new java.awt.Color(6, 193, 103));
        precioTExto.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        precioTExto.setForeground(new java.awt.Color(0, 0, 0));
        precioTExto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        precioTExto.setText("Precio");
        background.add(precioTExto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 60, 20));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 450, 20));

        ingredientesTexto.setBackground(new java.awt.Color(6, 193, 103));
        ingredientesTexto.setFont(new java.awt.Font("Roboto Medium", 2, 18)); // NOI18N
        ingredientesTexto.setForeground(new java.awt.Color(0, 0, 0));
        ingredientesTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ingredientesTexto.setText("Añada los ingredientes de 1 en 1");
        background.add(ingredientesTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 270, 20));

        imagenTexto.setBackground(new java.awt.Color(6, 193, 103));
        imagenTexto.setFont(new java.awt.Font("Roboto Medium", 2, 18)); // NOI18N
        imagenTexto.setForeground(new java.awt.Color(0, 0, 0));
        imagenTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        imagenTexto.setText("Seleccione la imagen que quiere para esta comida");
        background.add(imagenTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 420, 20));

        ingredientesInfo.setBackground(new java.awt.Color(255, 255, 255));
        ingredientesInfo.setForeground(new java.awt.Color(0, 0, 0));
        ingredientesInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        ingredientesInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredientesInfoActionPerformed(evt);
            }
        });
        background.add(ingredientesInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 260, 40));
        background.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 450, 10));

        elegirImagenBoton.setBackground(new java.awt.Color(6, 193, 103));
        elegirImagenBoton.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        elegirImagenBoton.setForeground(new java.awt.Color(0, 0, 0));
        elegirImagenBoton.setText("Elegir Imagen");
        elegirImagenBoton.setBorder(null);
        elegirImagenBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        elegirImagenBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                elegirImagenBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                elegirImagenBotonMouseExited(evt);
            }
        });
        elegirImagenBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elegirImagenBotonActionPerformed(evt);
            }
        });
        background.add(elegirImagenBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 160, 70));

        borrarImagen.setBackground(new java.awt.Color(6, 193, 103));
        borrarImagen.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        borrarImagen.setForeground(new java.awt.Color(0, 0, 0));
        borrarImagen.setText("Borrar");
        borrarImagen.setBorder(null);
        borrarImagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borrarImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                borrarImagenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                borrarImagenMouseExited(evt);
            }
        });
        borrarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarImagenActionPerformed(evt);
            }
        });
        background.add(borrarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 160, 70));

        annadirIngredienteBoton.setBackground(new java.awt.Color(6, 193, 103));
        annadirIngredienteBoton.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        annadirIngredienteBoton.setForeground(new java.awt.Color(0, 0, 0));
        annadirIngredienteBoton.setText("AÑADIR");
        annadirIngredienteBoton.setBorder(null);
        annadirIngredienteBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        annadirIngredienteBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                annadirIngredienteBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                annadirIngredienteBotonMouseExited(evt);
            }
        });
        annadirIngredienteBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annadirIngredienteBotonActionPerformed(evt);
            }
        });
        background.add(annadirIngredienteBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 160, 70));
        background.add(jLabelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 390, 190));
        jLabelImagen.setIcon(new ImageIcon("Imagenes/fondoNegro.png"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BarraFuncionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraFuncionesMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
        
    }//GEN-LAST:event_BarraFuncionesMousePressed

    private void BarraFuncionesMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraFuncionesMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BarraFuncionesMouseDragged

    private void exitTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextoMouseClicked
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_exitTextoMouseClicked

    private void exitTextoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextoMouseEntered
        // TODO add your handling code here:
        botonExit.setBackground(Color.red);
        exitTexto.setForeground(Color.WHITE);
    }//GEN-LAST:event_exitTextoMouseEntered

    private void exitTextoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextoMouseExited
        // TODO add your handling code here:
        botonExit.setBackground(Color.WHITE);
        exitTexto.setForeground(Color.BLACK);
    }//GEN-LAST:event_exitTextoMouseExited

    private void cerrarSesionTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionTextoMouseClicked
        // TODO add your handling code here:

        //Le advertimos de lo que va a hacer
        int respuestaUsuario = JOptionPane.showConfirmDialog(this, "¿Seguro que desea cerrar sesion?", "CERRAR SESIÓN"
            ,JOptionPane.YES_NO_OPTION );
        if(respuestaUsuario == JOptionPane.YES_OPTION)
        {
            //Le llevamos a la ventana de Inicio de sesion.
            InicioSesion cerrarSesion = new InicioSesion();
            cerrarSesion.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_cerrarSesionTextoMouseClicked

    private void cerrarSesionTextoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionTextoMouseEntered
        // TODO add your handling code here:
        cerrarSesionTexto.setForeground(Color.RED);
    }//GEN-LAST:event_cerrarSesionTextoMouseEntered

    private void cerrarSesionTextoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionTextoMouseExited
        // TODO add your handling code here:
        cerrarSesionTexto.setForeground(Color.BLACK);
    }//GEN-LAST:event_cerrarSesionTextoMouseExited

    private void atrasBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasBotonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_atrasBotonMouseClicked

    private void atrasBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasBotonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_atrasBotonMouseEntered

    private void atrasBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasBotonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_atrasBotonMouseExited

    private void atrasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBotonActionPerformed
        // TODO add your handling code here:
        ConsultaRestaurantes ventanaAnterior = new ConsultaRestaurantes();
        ventanaAnterior.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_atrasBotonActionPerformed

    private void nombreInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreInfoActionPerformed

    private void precioInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioInfoActionPerformed

    private void ingredientesInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredientesInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingredientesInfoActionPerformed

    private void elegirImagenBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elegirImagenBotonMouseEntered
        // TODO add your handling code here:
        elegirImagenBoton.setForeground(Color.BLUE);
    }//GEN-LAST:event_elegirImagenBotonMouseEntered

    private void elegirImagenBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elegirImagenBotonMouseExited
        // TODO add your handling code here:
        elegirImagenBoton.setForeground(Color.BLACK);
    }//GEN-LAST:event_elegirImagenBotonMouseExited

    private void elegirImagenBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elegirImagenBotonActionPerformed
        // TODO add your handling code here:
        try 
        {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.addChoosableFileFilter(new ImageFilter());
            fileChooser.setAcceptAllFileFilterUsed(false);
            ImageIcon imagenFondo = new ImageIcon("Imagenes/fondoNegro.png");

            int option = fileChooser.showOpenDialog(this);
            if (option == JFileChooser.APPROVE_OPTION) 
            {
                file = fileChooser.getSelectedFile();
                rutaImagen = file.getAbsolutePath();
                nombreImagen = file.getName();
                String[] aux = nombreImagen.split("\\.");
                ImageIcon imagen = new ImageIcon(rutaImagen);
                ImageIcon imgRedimensionada = new ImageIcon(imagen.getImage().getScaledInstance(jLabelImagen.getWidth(), jLabelImagen.getHeight(), 1));
                jLabelImagen.setIcon(imgRedimensionada);
                Sistema.setImagenActual(nombreImagen); //Mando al sistema el nombre de la imagen, ejemplo: "imagen.png".
                //Guardo la imagen
                bimage = ImageIO.read(file);
                File fout = new File("./Imagenes/" + nombreImagen);
                ImageIO.write(bimage, extension, fout);

            } 
            else 
            {
                jLabelImagen.setIcon(imagenFondo);
                JOptionPane.showMessageDialog(this, "Ningúna imagen seleccinada", "Mensaje", JOptionPane.ERROR_MESSAGE);
                Sistema.setImagenActual("fondoNegro.png"); //Mando al sistema el nombre de la imagen, ejemplo: "imagen.png".

            }
        }
        catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar imagen");
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, "Seleccione primero una imagen");
        }

    }//GEN-LAST:event_elegirImagenBotonActionPerformed

    private void borrarImagenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarImagenMouseEntered
        // TODO add your handling code here:
        borrarImagen.setForeground(Color.RED);
    }//GEN-LAST:event_borrarImagenMouseEntered

    private void borrarImagenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarImagenMouseExited
        // TODO add your handling code here:
        borrarImagen.setForeground(Color.BLACK);
    }//GEN-LAST:event_borrarImagenMouseExited

    private void borrarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarImagenActionPerformed
        // TODO add your handling code here:
        try 
        {
            //Cargo la imagen
            ImageIcon imagen = new ImageIcon("Imagenes/fondoNegro.png");
            //Pongo la imagen como icono en el jLabel
            jLabelImagen.setIcon(imagen);
            //Establezco la imagen actual
            Sistema.setImagenActual("fondoNegro.png");
        }  
        catch (Exception e) 
        {
            System.out.println("Error: " + e.toString());
        }

    }//GEN-LAST:event_borrarImagenActionPerformed

    private void annadirIngredienteBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_annadirIngredienteBotonMouseEntered
        // TODO add your handling code here:
        annadirIngredienteBoton.setForeground(Color.BLUE);
    }//GEN-LAST:event_annadirIngredienteBotonMouseEntered

    private void annadirIngredienteBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_annadirIngredienteBotonMouseExited
        // TODO add your handling code here:
        annadirIngredienteBoton.setForeground(Color.BLACK);
    }//GEN-LAST:event_annadirIngredienteBotonMouseExited

    private void annadirIngredienteBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annadirIngredienteBotonActionPerformed
        // TODO add your handling code here:
        if(Sistema.esStringCorrecto(ingredientesInfo.getText()))
        {
            listaIngredientes.add(ingredientesInfo.getText());
            JOptionPane.showMessageDialog(this, "Ingrediente añadido con exito", "INFO", JOptionPane.INFORMATION_MESSAGE);
        }
        ingredientesInfo.setText(""); //Reiniciamos el campo de texto SIEMPRE
    }//GEN-LAST:event_annadirIngredienteBotonActionPerformed

    private void hechoBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hechoBotonMouseEntered
        // TODO add your handling code here:
        hechoBoton.setForeground(Color.BLUE);
    }//GEN-LAST:event_hechoBotonMouseEntered

    private void hechoBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hechoBotonMouseExited
        // TODO add your handling code here:
        hechoBoton.setForeground(Color.BLACK);
    }//GEN-LAST:event_hechoBotonMouseExited

    private void hechoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hechoBotonActionPerformed
        // TODO add your handling code here:
        if
                (!Sistema.esStringCorrecto(nombreInfo.getText()) ||
                !Sistema.esStringCorrecto(precioInfo.getText())  
                )
        {
            System.out.println("Falta alguna casilla por rellenar");        //Info para desarrolladores
        }
        else if(listaIngredientes.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Debe de añadir al menos 1 ingrediente", "Faltan ingredientes", JOptionPane.WARNING_MESSAGE);
        }
        else if(!Sistema.esImagenCorrecta(Sistema.getImagenActual()))
        {
            System.out.println("El usuario no selecciono ninguna imagen");  //Uso exclusivo de desarrolladores
        }
        else        //En esta sentencia tmb se comprueba si la comida existe con metodos de la clase Sistema.
        {
            //Si pasaron todos los filtros anteriores significa que se puede crear la comida
            Comida comida = new Comida(nombreInfo.getText(), listaIngredientes, precioInfo.getText(), Sistema.getImagenActual());
            //Guardo la comida en el archivo *.dat y ademas la cargo en la lista de comidas
            if(Sistema.anadirComida(comida))
            {
                Sistema.guardarDatosComidas();
                //Le confirmamo que la comida se ha creado
                JOptionPane.showMessageDialog(this, "Comida creada con exito", "INFO", JOptionPane.INFORMATION_MESSAGE);
                //Sale de la ventana
                ConsultaRestaurantes ventana = new ConsultaRestaurantes();
                ventana.setVisible(true);
                this.setVisible(false);
            }
            
            
        }
    }//GEN-LAST:event_hechoBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearComida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraFunciones;
    private javax.swing.JPanel FondoVerdeDerecha;
    private javax.swing.JButton annadirIngredienteBoton;
    private javax.swing.JButton atrasBoton;
    private javax.swing.JPanel background;
    private javax.swing.JButton borrarImagen;
    private javax.swing.JPanel botonExit;
    private javax.swing.JLabel cerrarSesionTexto;
    private javax.swing.JLabel crearComidaTexto;
    private javax.swing.JLabel eatsTexto;
    private javax.swing.JButton elegirImagenBoton;
    private javax.swing.JLabel exitTexto;
    private javax.swing.JButton hechoBoton;
    private javax.swing.JLabel imagenTexto;
    private javax.swing.JTextField ingredientesInfo;
    private javax.swing.JLabel ingredientesTexto;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel javaTexto;
    private javax.swing.JTextField nombreInfo;
    private javax.swing.JLabel nombreTexto;
    private javax.swing.JFormattedTextField precioInfo;
    private javax.swing.JLabel precioTExto;
    // End of variables declaration//GEN-END:variables
}
