package InterfazJavaEat;


//IMPORTES
import ClasesJavaEat.Sistema;
import java.awt.Color;
import java.io.Serializable;
import javax.swing.JOptionPane;




/**
 * -Clase que muestra al administrador las distintas opciones que tiene.
 * @author David Sanchez
 * @version 1.0
 * @since 23/05/2023
 * @see Sistema
 * @see Color
 * @see Serializable
 * @see JOptionPane
 */
public class InicioAdmin  extends javax.swing.JFrame implements Serializable{

    
    
    int xMouse,yMouse;
    
    
    public InicioAdmin() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        //Actualizamos los datos como siempre
        Sistema.cargarDatosClientes();
        Sistema.cargarDatosEmpresas();
        Sistema.cargarDatosRestaurantes();
        Sistema.cargarDatosComidas();
        Sistema.cargarDatosVentasClientes();
        Sistema.cargarDatosVentasEmpresas();
        Sistema.cargarDatosVentasCatering();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        FondoVerdeDerecha = new javax.swing.JPanel();
        javaTexto = new javax.swing.JLabel();
        eatsTexto = new javax.swing.JLabel();
        cerrarSesionTexto = new javax.swing.JLabel();
        BarraFunciones = new javax.swing.JPanel();
        botonExit = new javax.swing.JPanel();
        exitTexto = new javax.swing.JLabel();
        consultaUsuarioBoton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        consultaRestaurantesBoton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        consultaVentasBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoVerdeDerecha.setBackground(new java.awt.Color(6, 193, 103));

        javaTexto.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        javaTexto.setForeground(new java.awt.Color(0, 0, 0));
        javaTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        javaTexto.setText("JAVA");

        eatsTexto.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        eatsTexto.setForeground(new java.awt.Color(0, 0, 0));
        eatsTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eatsTexto.setText("EATS");

        cerrarSesionTexto.setBackground(new java.awt.Color(255, 255, 255));
        cerrarSesionTexto.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        cerrarSesionTexto.setForeground(new java.awt.Color(0, 0, 0));
        cerrarSesionTexto.setText("Cerrar Sesión");
        cerrarSesionTexto.setBorder(null);
        cerrarSesionTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrarSesionTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarSesionTextoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarSesionTextoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarSesionTextoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout FondoVerdeDerechaLayout = new javax.swing.GroupLayout(FondoVerdeDerecha);
        FondoVerdeDerecha.setLayout(FondoVerdeDerechaLayout);
        FondoVerdeDerechaLayout.setHorizontalGroup(
            FondoVerdeDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eatsTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
            .addComponent(javaTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoVerdeDerechaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrarSesionTexto)
                .addContainerGap())
        );
        FondoVerdeDerechaLayout.setVerticalGroup(
            FondoVerdeDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoVerdeDerechaLayout.createSequentialGroup()
                .addComponent(cerrarSesionTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(javaTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eatsTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
        );

        background.add(FondoVerdeDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 280, 550));

        BarraFunciones.setBackground(new java.awt.Color(255, 255, 255));
        BarraFunciones.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraFuncionesMouseDragged(evt);
            }
        });
        BarraFunciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraFuncionesMousePressed(evt);
            }
        });

        botonExit.setBackground(new java.awt.Color(255, 255, 255));

        exitTexto.setBackground(new java.awt.Color(255, 255, 255));
        exitTexto.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        exitTexto.setForeground(new java.awt.Color(0, 0, 0));
        exitTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTexto.setText("X");
        exitTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTextoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTextoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTextoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botonExitLayout = new javax.swing.GroupLayout(botonExit);
        botonExit.setLayout(botonExitLayout);
        botonExitLayout.setHorizontalGroup(
            botonExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        botonExitLayout.setVerticalGroup(
            botonExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BarraFuncionesLayout = new javax.swing.GroupLayout(BarraFunciones);
        BarraFunciones.setLayout(BarraFuncionesLayout);
        BarraFuncionesLayout.setHorizontalGroup(
            BarraFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraFuncionesLayout.createSequentialGroup()
                .addComponent(botonExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 869, Short.MAX_VALUE))
        );
        BarraFuncionesLayout.setVerticalGroup(
            BarraFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraFuncionesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(BarraFunciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 40));

        consultaUsuarioBoton.setBackground(new java.awt.Color(6, 193, 103));
        consultaUsuarioBoton.setFont(new java.awt.Font("Roboto Medium", 2, 18)); // NOI18N
        consultaUsuarioBoton.setForeground(new java.awt.Color(0, 0, 0));
        consultaUsuarioBoton.setText("CONSULTA USUARIOS");
        consultaUsuarioBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultaUsuarioBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consultaUsuarioBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                consultaUsuarioBotonMouseExited(evt);
            }
        });
        consultaUsuarioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaUsuarioBotonActionPerformed(evt);
            }
        });
        background.add(consultaUsuarioBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 290, 80));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 640, 30));

        consultaRestaurantesBoton.setBackground(new java.awt.Color(6, 193, 103));
        consultaRestaurantesBoton.setFont(new java.awt.Font("Roboto Medium", 2, 18)); // NOI18N
        consultaRestaurantesBoton.setForeground(new java.awt.Color(0, 0, 0));
        consultaRestaurantesBoton.setText("CONSULTA RESTAURANTES");
        consultaRestaurantesBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultaRestaurantesBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consultaRestaurantesBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                consultaRestaurantesBotonMouseExited(evt);
            }
        });
        consultaRestaurantesBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaRestaurantesBotonActionPerformed(evt);
            }
        });
        background.add(consultaRestaurantesBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 290, 80));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 640, 80));

        consultaVentasBoton.setBackground(new java.awt.Color(6, 193, 103));
        consultaVentasBoton.setFont(new java.awt.Font("Roboto Medium", 2, 18)); // NOI18N
        consultaVentasBoton.setForeground(new java.awt.Color(0, 0, 0));
        consultaVentasBoton.setText("CONSULTA VENTAS");
        consultaVentasBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultaVentasBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consultaVentasBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                consultaVentasBotonMouseExited(evt);
            }
        });
        consultaVentasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaVentasBotonActionPerformed(evt);
            }
        });
        background.add(consultaVentasBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 290, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BarraFuncionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraFuncionesMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
        
    }//GEN-LAST:event_BarraFuncionesMousePressed

    private void BarraFuncionesMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraFuncionesMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BarraFuncionesMouseDragged

    private void exitTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextoMouseClicked
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_exitTextoMouseClicked

    private void exitTextoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextoMouseEntered
        // TODO add your handling code here:
        botonExit.setBackground(Color.red);
        exitTexto.setForeground(Color.WHITE);
    }//GEN-LAST:event_exitTextoMouseEntered

    private void exitTextoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextoMouseExited
        // TODO add your handling code here:
        botonExit.setBackground(Color.WHITE);
        exitTexto.setForeground(Color.BLACK);
    }//GEN-LAST:event_exitTextoMouseExited

    private void cerrarSesionTextoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionTextoMouseEntered
        // TODO add your handling code here:
        cerrarSesionTexto.setForeground(Color.RED);
    }//GEN-LAST:event_cerrarSesionTextoMouseEntered

    private void cerrarSesionTextoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionTextoMouseExited
        // TODO add your handling code here:
        cerrarSesionTexto.setForeground(Color.BLACK);
    }//GEN-LAST:event_cerrarSesionTextoMouseExited

    private void cerrarSesionTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionTextoMouseClicked
        // TODO add your handling code here:
        
        //Le advertimos de lo que va a hacer
        int respuestaUsuario = JOptionPane.showConfirmDialog(this, "¿Seguro que desea cerrar sesion?", "CERRAR SESIÓN"
                ,JOptionPane.YES_NO_OPTION );
        if(respuestaUsuario == JOptionPane.YES_OPTION)
        {
            //Le llevamos a la ventana de Inicio de sesion.
            InicioSesion cerrarSesion = new InicioSesion();
            cerrarSesion.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_cerrarSesionTextoMouseClicked

    private void consultaUsuarioBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaUsuarioBotonMouseEntered
        // TODO add your handling code here:
        consultaUsuarioBoton.setForeground(Color.BLUE);
        
    }//GEN-LAST:event_consultaUsuarioBotonMouseEntered

    private void consultaUsuarioBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaUsuarioBotonMouseExited
        // TODO add your handling code here:
        consultaUsuarioBoton.setForeground(Color.BLACK);
    }//GEN-LAST:event_consultaUsuarioBotonMouseExited

    private void consultaVentasBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaVentasBotonMouseEntered
        // TODO add your handling code here:
        consultaVentasBoton.setForeground(Color.BLUE);
    }//GEN-LAST:event_consultaVentasBotonMouseEntered

    private void consultaVentasBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaVentasBotonMouseExited
        // TODO add your handling code here:
        consultaVentasBoton.setForeground(Color.BLACK);
    }//GEN-LAST:event_consultaVentasBotonMouseExited

    private void consultaRestaurantesBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaRestaurantesBotonMouseEntered
        // TODO add your handling code here:
        consultaRestaurantesBoton.setForeground(Color.BLUE);
    }//GEN-LAST:event_consultaRestaurantesBotonMouseEntered

    private void consultaRestaurantesBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaRestaurantesBotonMouseExited
        // TODO add your handling code here:
        consultaRestaurantesBoton.setForeground(Color.BLACK);
    }//GEN-LAST:event_consultaRestaurantesBotonMouseExited

    private void consultaRestaurantesBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaRestaurantesBotonActionPerformed
        // TODO add your handling code here:
        ConsultaRestaurantes abrirVentana = new ConsultaRestaurantes();
        abrirVentana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_consultaRestaurantesBotonActionPerformed

    private void consultaUsuarioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaUsuarioBotonActionPerformed
        // TODO add your handling code here:
        ConsultaUsuarios abrirVentana = new ConsultaUsuarios();
        abrirVentana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_consultaUsuarioBotonActionPerformed

    private void consultaVentasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaVentasBotonActionPerformed
        // TODO add your handling code here:
        ConsultaVentas abrirVentana = new ConsultaVentas();
        abrirVentana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_consultaVentasBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraFunciones;
    private javax.swing.JPanel FondoVerdeDerecha;
    private javax.swing.JPanel background;
    private javax.swing.JPanel botonExit;
    private javax.swing.JLabel cerrarSesionTexto;
    private javax.swing.JButton consultaRestaurantesBoton;
    private javax.swing.JButton consultaUsuarioBoton;
    private javax.swing.JButton consultaVentasBoton;
    private javax.swing.JLabel eatsTexto;
    private javax.swing.JLabel exitTexto;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel javaTexto;
    // End of variables declaration//GEN-END:variables
}
