package InterfazJavaEat;



//IMPORTES
import ClasesJavaEat.Direccion;
import ClasesJavaEat.Empresa;
import ClasesJavaEat.Sistema;
import ClasesJavaEat.TarjetaDeCredito;
import java.awt.Color;
import java.io.Serializable;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;




/**
 * Clase encargada de ser capaz de modificar los datos que la {@link Empresa} quiera.
 * @author David Sanchez
 * @version 1.0
 * @since 23/05/2023
 * @see Direccion
 * @see Empresa
 * @see Sistema
 * @see TarjetaDeCredito
 * @see Color
 * @see Serializable
 * @see ImageIcon
 * @see JOptionPane
 */
public class ModificarDatosEmpresa extends javax.swing.JFrame implements Serializable {

    int xMouse,yMouse;
   
    
    public ModificarDatosEmpresa() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        //Actualizamos los datos como siempre
        Sistema.cargarDatosClientes();
        Sistema.cargarDatosEmpresas();
        Sistema.cargarDatosRestaurantes();
        Sistema.cargarDatosComidas();
        Sistema.cargarDatosVentasClientes();
        Sistema.cargarDatosVentasEmpresas();
        Sistema.cargarDatosVentasCatering();
        
        //Establecemos todos los campos de texto con los datos del cliente
        cifInfo.setText(Sistema.getEmpresaActual().getCif());
        nombreUsuarioInfo.setText(Sistema.getEmpresaActual().getNombre());
        correoInfo.setText(Sistema.getEmpresaActual().getCorreoElectronico());
        claveInfo.setText(Sistema.getEmpresaActual().getClave());
        calleInfo.setText(Sistema.getEmpresaActual().getDireccion().getCalle());
        numeroInfo.setText(Sistema.getEmpresaActual().getDireccion().getNumeroCalle());
        codigoPostalInfo.setText(Sistema.getEmpresaActual().getDireccion().getCodigoPostal());
        ciudadInfo.setText(Sistema.getEmpresaActual().getDireccion().getCiudad());
        nombreTitularInfo.setText(Sistema.getEmpresaActual().getTarjetaDeCredito().getNombreTitular());
        numeroTarjetaInfo.setText(Sistema.getEmpresaActual().getTarjetaDeCredito().getNumeroDeTarjeta());
        fechaCaducidadInfo.setText(Sistema.getEmpresaActual().getTarjetaDeCredito().getFechaDeCaducidad());
        telefonoInfo.setText(Sistema.getEmpresaActual().getTelefono());
        webInfo.setText(Sistema.getEmpresaActual().getWeb());
        
        //Procedemos a eliminar la empresa de la base de datos
        String CIF = Sistema.getEmpresaActual().getCif();
        
        
        //Busco la empresa que se quiere eliminar
        int index = -1;
        for (Empresa empresa : Sistema.getListaEmpresas()) 
            {
                index++;
                if(empresa.getCif().equals(CIF))
                {
                        Sistema.eliminarEmpresa(index);
                        break; //Para que no siga recorriendo la lista
                }
            }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        FondoVerdeDerecha = new javax.swing.JPanel();
        javaTexto = new javax.swing.JLabel();
        eatsTexto = new javax.swing.JLabel();
        atrasBoton = new javax.swing.JButton();
        entrarBoton = new javax.swing.JButton();
        darDeBajaBoton = new javax.swing.JButton();
        empresaTexto = new javax.swing.JLabel();
        BarraFunciones = new javax.swing.JPanel();
        botonExit = new javax.swing.JPanel();
        exitTexto = new javax.swing.JLabel();
        cifTexto = new javax.swing.JLabel();
        cifInfo = new javax.swing.JFormattedTextField();
        jSeparator2 = new javax.swing.JSeparator();
        claveTexto = new javax.swing.JLabel();
        calleTexto = new javax.swing.JLabel();
        nombreUsuarioTexto = new javax.swing.JLabel();
        correoTexto = new javax.swing.JLabel();
        numeroTexto = new javax.swing.JLabel();
        codigoPostaltexto = new javax.swing.JLabel();
        telefonoTexto = new javax.swing.JLabel();
        ciudadTexto = new javax.swing.JLabel();
        nombreUsuarioInfo = new javax.swing.JTextField();
        telefonoInfo = new javax.swing.JFormattedTextField();
        correoInfo = new javax.swing.JTextField();
        claveInfo = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        codigoPostalInfo = new javax.swing.JFormattedTextField();
        numeroInfo = new javax.swing.JTextField();
        calleInfo = new javax.swing.JTextField();
        ciudadInfo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        fechaCaducidadTexto = new javax.swing.JLabel();
        numeroTarjetaTexto = new javax.swing.JLabel();
        tarjetaDeCreditoTexto = new javax.swing.JLabel();
        nombreTitularTexto = new javax.swing.JLabel();
        fechaCaducidadInfo = new javax.swing.JFormattedTextField();
        nombreTitularInfo = new javax.swing.JTextField();
        numeroTarjetaInfo = new javax.swing.JFormattedTextField();
        webTexto = new javax.swing.JLabel();
        webInfo = new javax.swing.JTextField();
        infoExtra = new javax.swing.JLabel();
        mostrarContraseñaBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoVerdeDerecha.setBackground(new java.awt.Color(6, 193, 103));

        javaTexto.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        javaTexto.setForeground(new java.awt.Color(0, 0, 0));
        javaTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        javaTexto.setText("JAVA");

        eatsTexto.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        eatsTexto.setForeground(new java.awt.Color(0, 0, 0));
        eatsTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eatsTexto.setText("EATS");

        atrasBoton.setBackground(new java.awt.Color(6, 193, 103));
        atrasBoton.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        atrasBoton.setForeground(new java.awt.Color(0, 0, 0));
        atrasBoton.setBorder(null);
        atrasBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atrasBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atrasBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atrasBotonMouseExited(evt);
            }
        });
        atrasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBotonActionPerformed(evt);
            }
        });

        entrarBoton.setBackground(new java.awt.Color(6, 193, 103));
        entrarBoton.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        entrarBoton.setForeground(new java.awt.Color(0, 0, 0));
        entrarBoton.setText("¡HECHO!");
        entrarBoton.setBorder(null);
        entrarBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entrarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entrarBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                entrarBotonMouseExited(evt);
            }
        });
        entrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarBotonActionPerformed(evt);
            }
        });

        darDeBajaBoton.setBackground(new java.awt.Color(6, 193, 103));
        darDeBajaBoton.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        darDeBajaBoton.setForeground(new java.awt.Color(0, 0, 0));
        darDeBajaBoton.setText("Dar de BAJA");
        darDeBajaBoton.setBorder(null);
        darDeBajaBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        darDeBajaBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                darDeBajaBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                darDeBajaBotonMouseExited(evt);
            }
        });
        darDeBajaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darDeBajaBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoVerdeDerechaLayout = new javax.swing.GroupLayout(FondoVerdeDerecha);
        FondoVerdeDerecha.setLayout(FondoVerdeDerechaLayout);
        FondoVerdeDerechaLayout.setHorizontalGroup(
            FondoVerdeDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eatsTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(javaTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoVerdeDerechaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(atrasBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoVerdeDerechaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FondoVerdeDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(darDeBajaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entrarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        FondoVerdeDerechaLayout.setVerticalGroup(
            FondoVerdeDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoVerdeDerechaLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(javaTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eatsTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(entrarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(darDeBajaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(atrasBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        atrasBoton.setIcon(new ImageIcon("Imagenes/logoAtras.png"));

        background.add(FondoVerdeDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 300, 710));

        empresaTexto.setBackground(new java.awt.Color(6, 193, 103));
        empresaTexto.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        empresaTexto.setForeground(new java.awt.Color(0, 0, 0));
        empresaTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        empresaTexto.setText("Empresa");
        background.add(empresaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 440, 60));

        BarraFunciones.setBackground(new java.awt.Color(255, 255, 255));
        BarraFunciones.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraFuncionesMouseDragged(evt);
            }
        });
        BarraFunciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraFuncionesMousePressed(evt);
            }
        });

        botonExit.setBackground(new java.awt.Color(255, 255, 255));

        exitTexto.setBackground(new java.awt.Color(255, 255, 255));
        exitTexto.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        exitTexto.setForeground(new java.awt.Color(0, 0, 0));
        exitTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTexto.setText("X");
        exitTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTextoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTextoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTextoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botonExitLayout = new javax.swing.GroupLayout(botonExit);
        botonExit.setLayout(botonExitLayout);
        botonExitLayout.setHorizontalGroup(
            botonExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        botonExitLayout.setVerticalGroup(
            botonExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BarraFuncionesLayout = new javax.swing.GroupLayout(BarraFunciones);
        BarraFunciones.setLayout(BarraFuncionesLayout);
        BarraFuncionesLayout.setHorizontalGroup(
            BarraFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraFuncionesLayout.createSequentialGroup()
                .addComponent(botonExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        BarraFuncionesLayout.setVerticalGroup(
            BarraFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraFuncionesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(BarraFunciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 900, 50));

        cifTexto.setBackground(new java.awt.Color(6, 193, 103));
        cifTexto.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        cifTexto.setForeground(new java.awt.Color(0, 0, 0));
        cifTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cifTexto.setText("CIF");
        background.add(cifTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 40, 20));

        cifInfo.setBackground(new java.awt.Color(255, 255, 255));
        cifInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cifInfo.setForeground(new java.awt.Color(0, 0, 0));
        try {
            cifInfo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U-########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cifInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cifInfoActionPerformed(evt);
            }
        });
        background.add(cifInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 260, 40));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 330, 20));

        claveTexto.setBackground(new java.awt.Color(6, 193, 103));
        claveTexto.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        claveTexto.setForeground(new java.awt.Color(0, 0, 0));
        claveTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        claveTexto.setText("Contraseña");
        background.add(claveTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 90, 30));

        calleTexto.setBackground(new java.awt.Color(6, 193, 103));
        calleTexto.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        calleTexto.setForeground(new java.awt.Color(0, 0, 0));
        calleTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        calleTexto.setText("Calle");
        background.add(calleTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 40, 20));

        nombreUsuarioTexto.setBackground(new java.awt.Color(6, 193, 103));
        nombreUsuarioTexto.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        nombreUsuarioTexto.setForeground(new java.awt.Color(0, 0, 0));
        nombreUsuarioTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nombreUsuarioTexto.setText("Nombre Usuario");
        background.add(nombreUsuarioTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 110, 20));

        correoTexto.setBackground(new java.awt.Color(6, 193, 103));
        correoTexto.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        correoTexto.setForeground(new java.awt.Color(0, 0, 0));
        correoTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        correoTexto.setText("Correo Electronico");
        background.add(correoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 120, -1));

        numeroTexto.setBackground(new java.awt.Color(6, 193, 103));
        numeroTexto.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        numeroTexto.setForeground(new java.awt.Color(0, 0, 0));
        numeroTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        numeroTexto.setText("Numero");
        background.add(numeroTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 70, 20));

        codigoPostaltexto.setBackground(new java.awt.Color(6, 193, 103));
        codigoPostaltexto.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        codigoPostaltexto.setForeground(new java.awt.Color(0, 0, 0));
        codigoPostaltexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        codigoPostaltexto.setText("Codigo Postal");
        background.add(codigoPostaltexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 90, 20));

        telefonoTexto.setBackground(new java.awt.Color(6, 193, 103));
        telefonoTexto.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        telefonoTexto.setForeground(new java.awt.Color(0, 0, 0));
        telefonoTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        telefonoTexto.setText("Teléfono");
        background.add(telefonoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 100, 30));

        ciudadTexto.setBackground(new java.awt.Color(6, 193, 103));
        ciudadTexto.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        ciudadTexto.setForeground(new java.awt.Color(0, 0, 0));
        ciudadTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ciudadTexto.setText("Ciudad");
        background.add(ciudadTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 50, 20));

        nombreUsuarioInfo.setBackground(new java.awt.Color(255, 255, 255));
        nombreUsuarioInfo.setForeground(new java.awt.Color(0, 0, 0));
        nombreUsuarioInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        nombreUsuarioInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUsuarioInfoActionPerformed(evt);
            }
        });
        background.add(nombreUsuarioInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 166, 260, 40));

        telefonoInfo.setBackground(new java.awt.Color(255, 255, 255));
        telefonoInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        telefonoInfo.setForeground(new java.awt.Color(0, 0, 0));
        try {
            telefonoInfo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefonoInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoInfoActionPerformed(evt);
            }
        });
        background.add(telefonoInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 260, 30));

        correoInfo.setBackground(new java.awt.Color(255, 255, 255));
        correoInfo.setForeground(new java.awt.Color(0, 0, 0));
        correoInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        correoInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoInfoActionPerformed(evt);
            }
        });
        background.add(correoInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 260, 40));

        claveInfo.setBackground(new java.awt.Color(255, 255, 255));
        claveInfo.setForeground(new java.awt.Color(0, 0, 0));
        claveInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        claveInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                claveInfoMouseClicked(evt);
            }
        });
        claveInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveInfoActionPerformed(evt);
            }
        });
        background.add(claveInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 260, 40));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 630, 10));

        codigoPostalInfo.setBackground(new java.awt.Color(255, 255, 255));
        codigoPostalInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        codigoPostalInfo.setForeground(new java.awt.Color(0, 0, 0));
        try {
            codigoPostalInfo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        codigoPostalInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoPostalInfoActionPerformed(evt);
            }
        });
        background.add(codigoPostalInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 130, 40));

        numeroInfo.setBackground(new java.awt.Color(255, 255, 255));
        numeroInfo.setForeground(new java.awt.Color(0, 0, 0));
        numeroInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        background.add(numeroInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 250, -1));

        calleInfo.setBackground(new java.awt.Color(255, 255, 255));
        calleInfo.setForeground(new java.awt.Color(0, 0, 0));
        calleInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        background.add(calleInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 250, 40));

        ciudadInfo.setBackground(new java.awt.Color(255, 255, 255));
        ciudadInfo.setForeground(new java.awt.Color(0, 0, 0));
        ciudadInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        ciudadInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadInfoActionPerformed(evt);
            }
        });
        background.add(ciudadInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 130, 40));
        background.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 630, 10));

        fechaCaducidadTexto.setBackground(new java.awt.Color(6, 193, 103));
        fechaCaducidadTexto.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        fechaCaducidadTexto.setForeground(new java.awt.Color(0, 0, 0));
        fechaCaducidadTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fechaCaducidadTexto.setText("Fecha Caducidad");
        background.add(fechaCaducidadTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 630, -1, 20));

        numeroTarjetaTexto.setBackground(new java.awt.Color(6, 193, 103));
        numeroTarjetaTexto.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        numeroTarjetaTexto.setForeground(new java.awt.Color(0, 0, 0));
        numeroTarjetaTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        numeroTarjetaTexto.setText("Numero Tarjeta");
        background.add(numeroTarjetaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 110, 20));

        tarjetaDeCreditoTexto.setBackground(new java.awt.Color(6, 193, 103));
        tarjetaDeCreditoTexto.setFont(new java.awt.Font("Roboto Medium", 2, 18)); // NOI18N
        tarjetaDeCreditoTexto.setForeground(new java.awt.Color(0, 0, 0));
        tarjetaDeCreditoTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tarjetaDeCreditoTexto.setText("Tarjeta De Credito");
        background.add(tarjetaDeCreditoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 150, 20));

        nombreTitularTexto.setBackground(new java.awt.Color(6, 193, 103));
        nombreTitularTexto.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        nombreTitularTexto.setForeground(new java.awt.Color(0, 0, 0));
        nombreTitularTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nombreTitularTexto.setText("Nombre Titular");
        background.add(nombreTitularTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 100, 20));

        fechaCaducidadInfo.setBackground(new java.awt.Color(255, 255, 255));
        fechaCaducidadInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        fechaCaducidadInfo.setForeground(new java.awt.Color(0, 0, 0));
        try {
            fechaCaducidadInfo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fechaCaducidadInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaCaducidadInfoActionPerformed(evt);
            }
        });
        background.add(fechaCaducidadInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, 130, 40));

        nombreTitularInfo.setBackground(new java.awt.Color(255, 255, 255));
        nombreTitularInfo.setForeground(new java.awt.Color(0, 0, 0));
        nombreTitularInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        nombreTitularInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTitularInfoActionPerformed(evt);
            }
        });
        background.add(nombreTitularInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 230, 40));

        numeroTarjetaInfo.setBackground(new java.awt.Color(255, 255, 255));
        numeroTarjetaInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        numeroTarjetaInfo.setForeground(new java.awt.Color(0, 0, 0));
        try {
            numeroTarjetaInfo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        numeroTarjetaInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroTarjetaInfoActionPerformed(evt);
            }
        });
        background.add(numeroTarjetaInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 640, 230, 40));

        webTexto.setBackground(new java.awt.Color(6, 193, 103));
        webTexto.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        webTexto.setForeground(new java.awt.Color(0, 0, 0));
        webTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        webTexto.setText("Web");
        background.add(webTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 100, -1));

        webInfo.setBackground(new java.awt.Color(255, 255, 255));
        webInfo.setForeground(new java.awt.Color(0, 0, 0));
        webInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        background.add(webInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 260, 40));

        infoExtra.setBackground(new java.awt.Color(0, 0, 0));
        infoExtra.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        infoExtra.setForeground(new java.awt.Color(0, 0, 0));
        infoExtra.setText("mm/yyyy");
        background.add(infoExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 600, -1, -1));

        mostrarContraseñaBox.setBackground(new java.awt.Color(255, 255, 255));
        mostrarContraseñaBox.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        mostrarContraseñaBox.setForeground(new java.awt.Color(0, 0, 0));
        mostrarContraseñaBox.setText("Mostrar contraseña");
        mostrarContraseñaBox.setBorder(null);
        mostrarContraseñaBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostrarContraseñaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarContraseñaBoxActionPerformed(evt);
            }
        });
        background.add(mostrarContraseñaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BarraFuncionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraFuncionesMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
        
    }//GEN-LAST:event_BarraFuncionesMousePressed

    private void BarraFuncionesMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraFuncionesMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BarraFuncionesMouseDragged

    private void exitTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextoMouseClicked
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_exitTextoMouseClicked

    private void exitTextoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextoMouseEntered
        // TODO add your handling code here:
        botonExit.setBackground(Color.red);
        exitTexto.setForeground(Color.WHITE);
    }//GEN-LAST:event_exitTextoMouseEntered

    private void exitTextoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextoMouseExited
        // TODO add your handling code here:
        botonExit.setBackground(Color.WHITE);
        exitTexto.setForeground(Color.BLACK);
    }//GEN-LAST:event_exitTextoMouseExited

    private void atrasBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasBotonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_atrasBotonMouseClicked

    private void atrasBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasBotonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_atrasBotonMouseEntered

    private void atrasBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasBotonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_atrasBotonMouseExited

    private void atrasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBotonActionPerformed
        // TODO add your handling code here:
        InicioEmpresa ventanaRegistro = new InicioEmpresa();
        ventanaRegistro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_atrasBotonActionPerformed

    private void cifInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cifInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cifInfoActionPerformed

    private void nombreUsuarioInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUsuarioInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreUsuarioInfoActionPerformed

    private void telefonoInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoInfoActionPerformed

    private void correoInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoInfoActionPerformed

    private void claveInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_claveInfoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_claveInfoMouseClicked

    private void claveInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claveInfoActionPerformed

    private void codigoPostalInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoPostalInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoPostalInfoActionPerformed

    private void ciudadInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudadInfoActionPerformed

    private void fechaCaducidadInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaCaducidadInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaCaducidadInfoActionPerformed

    private void nombreTitularInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTitularInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTitularInfoActionPerformed

    private void numeroTarjetaInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroTarjetaInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroTarjetaInfoActionPerformed

    private void entrarBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarBotonMouseEntered
        // TODO add your handling code here:
        entrarBoton.setForeground(Color.BLUE);
    }//GEN-LAST:event_entrarBotonMouseEntered

    private void entrarBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarBotonMouseExited
        // TODO add your handling code here:
        entrarBoton.setForeground(Color.BLACK);
    }//GEN-LAST:event_entrarBotonMouseExited

    private void entrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarBotonActionPerformed
        
        if(
                //Comprobamos que no haya ninguna casilla vacia
                !Sistema.esStringCorrecto(cifInfo.getText())                                    ||
                !Sistema.esStringCorrecto(nombreUsuarioInfo.getText())                          ||
                !Sistema.esStringCorrecto(String.valueOf(claveInfo.getPassword()))              ||
                !Sistema.esStringCorrecto(webInfo.getText())                                    ||
                !Sistema.esStringCorrecto(calleInfo.getText())                                  ||
                !Sistema.esStringCorrecto(numeroInfo.getText())                                 ||
                !Sistema.esStringCorrecto(String.valueOf(codigoPostalInfo.getText()))       ||
                !Sistema.esStringCorrecto(ciudadInfo.getText())                                 ||
                !Sistema.esStringCorrecto(nombreTitularInfo.getText())                          ||
                !Sistema.esStringCorrecto(numeroTarjetaInfo.getText())                          ||
                !Sistema.esStringCorrecto(fechaCaducidadInfo.getText())                                  
            
           )
        {
            //Info admin
            System.out.println("Falta alguna casilla por rellenar");      //Uso exlusivo para desarolladores
        }
        //Ahora comprobamos la fecha
        else if(!Sistema.esFechaCorrecta(fechaCaducidadInfo.getText()))
        {
            //Reiniciamos campo de texto
            fechaCaducidadInfo.setText("");
        }
        //Ahora si el correo es valido
        else if(!Sistema.esCorreoCorrecto(correoInfo.getText()))
        {
            //Reiniciamos campo de texto
            correoInfo.setText("");
        }
        else
        //Si el usuario pasa todas estas pruebas significa que puede realizar el registro
        {
            //Creamos la direccion
            Direccion direccion = new Direccion(calleInfo.getText(), numeroInfo.getText()
                    ,String.valueOf(codigoPostalInfo.getText()), ciudadInfo.getText());
            
            //Creamos la tarjeta de Credito
            TarjetaDeCredito tarjetaDeCredito = new TarjetaDeCredito(nombreTitularInfo.getText()
                                                            , numeroTarjetaInfo.getText()
                                                            , fechaCaducidadInfo.getText());
            
            //Creamos la empresa
            Empresa empresa = new Empresa(cifInfo.getText(), nombreUsuarioInfo.getText(), 
                                            correoInfo.getText(), String.valueOf(claveInfo.getPassword()),
                                            direccion, tarjetaDeCredito, telefonoInfo.getText(), webInfo.getText());
            
            //Procedemos con el registro
            if(Sistema.anadirEmpresa(empresa))      //Si la empresa esta ya registrada se comprueba en el metodo.
            {
            Sistema.guardarDatosEmpresas();
            JOptionPane.showMessageDialog(null, "Datos cambiados correctamente" , "INFO", JOptionPane.INFORMATION_MESSAGE);
            //Cerramos la ventana
            InicioSesion ventanaInicioSesion = new InicioSesion();
            ventanaInicioSesion.setVisible(true);
            this.setVisible(false);
            }
            else //Si entra aqui significa que la empresa ya estaba creada, le mandamos al Inicio de Sesion
            {
                //Cerramos la ventana
                InicioSesion ventanaInicioSesion = new InicioSesion();
                ventanaInicioSesion.setVisible(true);
                this.setVisible(false);
            }
        }
        
        

        
    }//GEN-LAST:event_entrarBotonActionPerformed

    private void mostrarContraseñaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarContraseñaBoxActionPerformed
        // TODO add your handling code here:
        if(mostrarContraseñaBox.isSelected())
        {
            claveInfo.setEchoChar((char)0);
        }
        else
        {
            claveInfo.setEchoChar('*');
        }
    }//GEN-LAST:event_mostrarContraseñaBoxActionPerformed

    private void darDeBajaBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_darDeBajaBotonMouseEntered
        // TODO add your handling code here:
        darDeBajaBoton.setForeground(Color.red);
    }//GEN-LAST:event_darDeBajaBotonMouseEntered

    private void darDeBajaBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_darDeBajaBotonMouseExited
        // TODO add your handling code here:
        darDeBajaBoton.setForeground(Color.BLACK);
    }//GEN-LAST:event_darDeBajaBotonMouseExited

    private void darDeBajaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darDeBajaBotonActionPerformed
        // TODO add your handling code here:
        
        int respuestaUsuario = JOptionPane.showConfirmDialog(this
                , "Seguro que deseas dar de baja tu cuenta"
                , "BORRADO DE CUENTA"
            ,JOptionPane.YES_NO_OPTION );
        
        if(respuestaUsuario == JOptionPane.YES_OPTION)
            {
            //Procedemos a eliminar el cliente de la base de datos
            String CIF = Sistema.getEmpresaActual().getCif();

            //Busco el cliente que se quiere eliminar
            int index = -1;
            for (Empresa empresa : Sistema.getListaEmpresas()) 
                {
                    index++;
                    if(empresa.getCif().equals(CIF))
                    {
                            Sistema.eliminarEmpresa(index);
                            break; //Para que no siga recorriendo la lista
                    }
                }
            //Guardo los datos
            Sistema.guardarDatosEmpresas();
            
            InicioSesion ventana = new InicioSesion();
            ventana.setVisible(true);
            this.setVisible(false);
            }
    }//GEN-LAST:event_darDeBajaBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarDatosEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarDatosEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarDatosEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarDatosEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarDatosEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraFunciones;
    private javax.swing.JPanel FondoVerdeDerecha;
    private javax.swing.JButton atrasBoton;
    private javax.swing.JPanel background;
    private javax.swing.JPanel botonExit;
    private javax.swing.JTextField calleInfo;
    private javax.swing.JLabel calleTexto;
    private javax.swing.JFormattedTextField cifInfo;
    private javax.swing.JLabel cifTexto;
    private javax.swing.JTextField ciudadInfo;
    private javax.swing.JLabel ciudadTexto;
    private javax.swing.JPasswordField claveInfo;
    private javax.swing.JLabel claveTexto;
    private javax.swing.JFormattedTextField codigoPostalInfo;
    private javax.swing.JLabel codigoPostaltexto;
    private javax.swing.JTextField correoInfo;
    private javax.swing.JLabel correoTexto;
    private javax.swing.JButton darDeBajaBoton;
    private javax.swing.JLabel eatsTexto;
    private javax.swing.JLabel empresaTexto;
    private javax.swing.JButton entrarBoton;
    private javax.swing.JLabel exitTexto;
    private javax.swing.JFormattedTextField fechaCaducidadInfo;
    private javax.swing.JLabel fechaCaducidadTexto;
    private javax.swing.JLabel infoExtra;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel javaTexto;
    private javax.swing.JCheckBox mostrarContraseñaBox;
    private javax.swing.JTextField nombreTitularInfo;
    private javax.swing.JLabel nombreTitularTexto;
    private javax.swing.JTextField nombreUsuarioInfo;
    private javax.swing.JLabel nombreUsuarioTexto;
    private javax.swing.JTextField numeroInfo;
    private javax.swing.JFormattedTextField numeroTarjetaInfo;
    private javax.swing.JLabel numeroTarjetaTexto;
    private javax.swing.JLabel numeroTexto;
    private javax.swing.JLabel tarjetaDeCreditoTexto;
    private javax.swing.JFormattedTextField telefonoInfo;
    private javax.swing.JLabel telefonoTexto;
    private javax.swing.JTextField webInfo;
    private javax.swing.JLabel webTexto;
    // End of variables declaration//GEN-END:variables
}
